INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Krajská nemocnice Liberec a.s.', 411651, 5867, 2905, 'Liberec');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Nemocnice Rudolfa a Stefanie Benešov, a.s.', 411677, 5899, 2981, 'Benešov');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Bílovecká nemocnice, a.s.', 411766, 5988, 3186, 'Bílovec');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Zdravotní ústav se sídlem v Ostravě - Brno', 411789, 5889, 3231, 'Brno');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Fakultní nemocnice u sv. Anny v Brně', 411653, 5869, 2911, 'Brno-střed');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Nemocnice s poliklinikou Česká Lípa a.s.', 411747, 5971, 3134, 'Česká Lípa');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Očkovací centrum Výstaviště České Budějovice (pavilon T1, vstup od Tesca)', 411685, 5910, 2996, 'České Budějovice');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Karlovarská krajská nemocnice a.s. - Cheb', 411828, 5866, 3312, 'Cheb');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('VITA s.r.o', 411802, 6010, 3259, 'Duchcov');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Nemocnice ve Frýdku-Místku, p.o.', 411745, 5969, 3128, 'Frýdek-Místek');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Nemocnice s poliklinikou Havířov, p.o.', 411820, 6026, 3301, 'Havířov');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Nemocnice TGM Hodonín', 411869, 5332, 2569, 'Hodonín');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Fakultní nemocnice Hradec Králové', 411675, 5898, 2976, 'Hradec Králové');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Nemocnice Hranice a.s.', 411721, 5949, 3073, 'Hranice');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Nemocnice Hustopeče, p.o.', 411804, 6013, 3268, 'Hustopeče');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Nemocnice Jablonec nad Nisou, p. o.', 411708, 5936, 3036, 'Jablonec nad Nisou');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Masarykova městská nemocnice a.s. (Jilemnice)', 411819, 5926, 3061, 'Jilemnice');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Karlovarská krajská nemocnice a.s.', 411650, 5866, 2902, 'Karlovy Vary');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Nemocnice s poliklinikou Karviná-Ráj', 411827, 6030, 3310, 'Karviná');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Karvinská hornická nemocnice a.s.', 411858, 6066, 3389, 'Karviná - Nové Město');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Oblastní nemocnice Kladno', 411661, 5877, 2935, 'Kladno');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Oblastní nemocnice Kolín', 411660, 5876, 2932, 'Kolín');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Kroměřížská nemocnice a.s.', 411816, 6023, 3296, 'Kroměříž');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Nemocnice Kutná Hora', 411720, 5947, 3067, 'Kutná Hora');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Nemocnice Neratovice', 411734, 5958, 3095, 'Neratovice');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Fakultní nemocnice Olomouc', 411652, 5868, 2908, 'Olomouc');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Vojenská nemocnice Olomouc', 411664, 5880, 2944, 'Olomouc');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Slezská nemocnice v Opavě', 411795, 6003, 3243, 'Opava');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('EUC Klinika Ostrava', 411697, 5925, 3021, 'Ostrava');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Zdravotní ústav se sídlem v Ostravě - Ostrava', 411788, 5889, 3230, 'Ostrava - Moravská Ostrava');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Městská nemocnice Ostrava, p.o.', 411801, 6009, 3256, 'Ostrava-Moravská Ostrava');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Fakultní nemocnice Ostrava', 411670, 5893, 2951, 'Ostrava - Poruba');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Fakultní Nemocnice Plzeň', 411649, 5865, 2899, 'Plzeň');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Fakultní nemocnice Královské Vinohrady', 411674, 5894, 2969, 'Praha 10 - Vinohrady');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Fakultní Thomayerova nemocnice', 411518, 5895, 2972, 'Praha 4 - Krč');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Fakultní nemocnice v Motole', 411655, 5871, 2917, 'Praha 5');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Nemocnice na Homolce', 411657, 5873, 2923, 'Praha 5');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Ústřední vojenská nemocnice - Očkovací centrum, pavilon L', 411839, 5892, 3341, 'Praha 6');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Fakultní nemocnice Bulovka', 411671, 5890, 2953, 'Praha 8');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Ústřední vojenská nemocnice - Ambulance ORT, pavilon A1', 411669, 5892, 2954, 'Praha, Břevnov');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Rokycanská nemocnice', 411758, 5981, 3165, 'Rokycany');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('MEDITERRA - Sedlčany s.r.o.', 411738, 6073, 3405, 'Sedlčany');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Nemocnice Sokolov', 411798, 6007, 3250, 'Sokolov');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Stodská nemocnice', 411763, 5986, 3180, 'Stod');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Nemocnice Třinec, p.o.', 411841, 6050, 3350, 'Třinec');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Oblastní nemocnice Trutnov a.s.', 411756, 5979, 3152, 'Trutnov');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Uherskohradišťská nemocnice a.s.', 411762, 5985, 3177, 'Uherské Hradiště');
INSERT INTO public.ockovaci_misto (nazev, service_id, operation_id, place_id, mesto) VALUES ('Vsetínská nemocnice', 411768, 5991, 3191, 'Vsetín');
