"""empty message

Revision ID: 09855c27cf19
Revises: 44a003e0c556
Create Date: 2021-04-02 21:08:29.181400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09855c27cf19'
down_revision = '44a003e0c556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_kraj_id_datum', 'kraje_metriky', ['kraj_id', 'datum'], unique=False)
    op.create_index(op.f('ix_ockovaci_mista_nrpzs_kod'), 'ockovaci_mista', ['nrpzs_kod'], unique=False)
    op.create_index(op.f('ix_ockovani_distribuce_cilove_ockovaci_misto_id'), 'ockovani_distribuce', ['cilove_ockovaci_misto_id'], unique=False)
    op.create_index(op.f('ix_ockovani_distribuce_ockovaci_misto_id'), 'ockovani_distribuce', ['ockovaci_misto_id'], unique=False)
    op.create_index(op.f('ix_ockovani_lide_kraj_nuts_kod'), 'ockovani_lide', ['kraj_nuts_kod'], unique=False)
    op.create_index(op.f('ix_ockovani_lide_zarizeni_kod'), 'ockovani_lide', ['zarizeni_kod'], unique=False)
    op.create_index(op.f('ix_ockovani_lide_profese_kraj_bydl_nuts'), 'ockovani_lide_profese', ['kraj_bydl_nuts'], unique=False)
    op.create_index(op.f('ix_ockovani_lide_profese_kraj_nuts_kod'), 'ockovani_lide_profese', ['kraj_nuts_kod'], unique=False)
    op.create_index(op.f('ix_ockovani_lide_profese_zarizeni_kod'), 'ockovani_lide_profese', ['zarizeni_kod'], unique=False)
    op.drop_column('ockovani_registrace', 'pocet_zmena')
    op.drop_column('ockovani_rezervace', 'maximalni_kapacita_zmena')
    op.drop_column('ockovani_rezervace', 'volna_kapacita_zmena')
    op.create_index('idx_okres_id_datum', 'okresy_metriky', ['okres_id', 'datum'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_okres_id_datum', table_name='okresy_metriky')
    op.add_column('ockovani_rezervace', sa.Column('volna_kapacita_zmena', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovani_rezervace', sa.Column('maximalni_kapacita_zmena', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovani_registrace', sa.Column('pocet_zmena', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ockovani_lide_profese_zarizeni_kod'), table_name='ockovani_lide_profese')
    op.drop_index(op.f('ix_ockovani_lide_profese_kraj_nuts_kod'), table_name='ockovani_lide_profese')
    op.drop_index(op.f('ix_ockovani_lide_profese_kraj_bydl_nuts'), table_name='ockovani_lide_profese')
    op.drop_index(op.f('ix_ockovani_lide_zarizeni_kod'), table_name='ockovani_lide')
    op.drop_index(op.f('ix_ockovani_lide_kraj_nuts_kod'), table_name='ockovani_lide')
    op.drop_index(op.f('ix_ockovani_distribuce_ockovaci_misto_id'), table_name='ockovani_distribuce')
    op.drop_index(op.f('ix_ockovani_distribuce_cilove_ockovaci_misto_id'), table_name='ockovani_distribuce')
    op.drop_index(op.f('ix_ockovaci_mista_nrpzs_kod'), table_name='ockovaci_mista')
    op.drop_index('idx_kraj_id_datum', table_name='kraje_metriky')
    # ### end Alembic commands ###
