"""empty message

Revision ID: 10aadf62ab2a
Revises: d30325fe4fb8
Create Date: 2021-11-10 18:20:01.827481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10aadf62ab2a'
down_revision = 'd30325fe4fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kapacity_nemocnic',
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('zz_kod', sa.Unicode(), nullable=False),
    sa.Column('zz_nazev', sa.Unicode(), nullable=False),
    sa.Column('kraj_nuts_kod', sa.Unicode(), nullable=False),
    sa.Column('luzka_standard_kyslik_kapacita_volna_covid_pozitivni', sa.Integer(), nullable=True),
    sa.Column('luzka_standard_kyslik_kapacita_volna_covid_negativni', sa.Integer(), nullable=True),
    sa.Column('luzka_standard_kyslik_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('luzka_hfno_cpap_kapacita_volna_covid_pozitivni', sa.Integer(), nullable=True),
    sa.Column('luzka_hfno_cpap_kapacita_volna_covid_negativni', sa.Integer(), nullable=True),
    sa.Column('luzka_hfno_cpap_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('luzka_upv_niv_kapacita_volna_covid_pozitivni', sa.Integer(), nullable=True),
    sa.Column('luzka_upv_niv_kapacita_volna_covid_negativni', sa.Integer(), nullable=True),
    sa.Column('luzka_upv_niv_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('inf_luzka_kyslik_kapacita_volna_covid_pozitivni', sa.Integer(), nullable=True),
    sa.Column('inf_luzka_kyslik_kapacita_volna_covid_negativni', sa.Integer(), nullable=True),
    sa.Column('inf_luzka_kyslik_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('inf_luzka_hfno_kapacita_volna_covid_pozitivni', sa.Integer(), nullable=True),
    sa.Column('inf_luzka_hfno_kapacita_volna_covid_negativni', sa.Integer(), nullable=True),
    sa.Column('inf_luzka_hfno_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('inf_luzka_upv_kapacita_volna_covid_pozitivni', sa.Integer(), nullable=True),
    sa.Column('inf_luzka_upv_kapacita_volna_covid_negativni', sa.Integer(), nullable=True),
    sa.Column('inf_luzka_upv_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('ventilatory_operacni_sal_kapacita_volna', sa.Integer(), nullable=True),
    sa.Column('ventilatory_operacni_sal_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('ecmo_kapacita_volna', sa.Integer(), nullable=True),
    sa.Column('ecmo_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('cvvhd_kapacita_volna', sa.Integer(), nullable=True),
    sa.Column('cvvhd_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('ventilatory_prenosne_kapacita_volna', sa.Integer(), nullable=True),
    sa.Column('ventilatory_prenosne_kapacita_celkem', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum', 'zz_kod', 'zz_nazev', 'kraj_nuts_kod')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kapacity_nemocnic')
    # ### end Alembic commands ###
