"""empty message

Revision ID: 12811ace3d10
Revises: 1ed9516441be
Create Date: 2021-04-30 22:20:52.606078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12811ace3d10'
down_revision = '1ed9516441be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ockovani_lide_profese', sa.Column('indikace_bezpecnostni_infrastruktura', sa.Boolean(), nullable=True))
    op.add_column('ockovani_lide_profese', sa.Column('indikace_chronicke_onemocneni', sa.Boolean(), nullable=True))
    op.execute("UPDATE ockovani_lide_profese SET indikace_bezpecnostni_infrastruktura = false, indikace_chronicke_onemocneni = false")
    op.execute('ALTER TABLE ockovani_lide_profese DROP CONSTRAINT ockovani_lide_profese_pkey')
    op.create_primary_key('ockovani_lide_profese_pkey', 'ockovani_lide_profese', ['datum', 'vakcina', 'zarizeni_kod', 'poradi_davky', 'vekova_skupina', 'kraj_bydl_nuts', 'indikace_zdravotnik', 'indikace_socialni_sluzby', 'indikace_ostatni', 'indikace_pedagog', 'indikace_skolstvi_ostatni', 'indikace_bezpecnostni_infrastruktura', 'indikace_chronicke_onemocneni'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ockovani_lide_profese', 'indikace_chronicke_onemocneni')
    op.drop_column('ockovani_lide_profese', 'indikace_bezpecnostni_infrastruktura')
    # ### end Alembic commands ###
