"""empty message

Revision ID: 1430d11d2ce8
Revises: d02dc7054d09
Create Date: 2021-03-20 20:07:43.879533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1430d11d2ce8'
down_revision = 'd02dc7054d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cr_metriky',
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('pocet_obyvatel_celkem', sa.Integer(), nullable=True),
    sa.Column('pocet_obyvatel_dospeli', sa.Integer(), nullable=True),
    sa.Column('rezervace_celkem', sa.Integer(), nullable=True),
    sa.Column('rezervace_celkem_zmena_den', sa.Integer(), nullable=True),
    sa.Column('rezervace_celkem_zmena_tyden', sa.Integer(), nullable=True),
    sa.Column('rezervace_cekajici', sa.Integer(), nullable=True),
    sa.Column('rezervace_cekajici_zmena_den', sa.Integer(), nullable=True),
    sa.Column('rezervace_cekajici_zmena_tyden', sa.Integer(), nullable=True),
    sa.Column('rezervace_kapacita', sa.Integer(), nullable=True),
    sa.Column('rezervace_kapacita_zmena_den', sa.Integer(), nullable=True),
    sa.Column('rezervace_kapacita_zmena_tyden', sa.Integer(), nullable=True),
    sa.Column('rezervace_kapacita_1', sa.Integer(), nullable=True),
    sa.Column('rezervace_kapacita_1_zmena_den', sa.Integer(), nullable=True),
    sa.Column('rezervace_kapacita_1_zmena_tyden', sa.Integer(), nullable=True),
    sa.Column('registrace_celkem', sa.Integer(), nullable=True),
    sa.Column('registrace_celkem_zmena_den', sa.Integer(), nullable=True),
    sa.Column('registrace_celkem_zmena_tyden', sa.Integer(), nullable=True),
    sa.Column('registrace_fronta', sa.Integer(), nullable=True),
    sa.Column('registrace_fronta_zmena_den', sa.Integer(), nullable=True),
    sa.Column('registrace_fronta_zmena_tyden', sa.Integer(), nullable=True),
    sa.Column('registrace_tydenni_uspesnost', sa.Float(), nullable=True),
    sa.Column('registrace_tydenni_uspesnost_zmena_den', sa.Float(), nullable=True),
    sa.Column('registrace_tydenni_uspesnost_zmena_tyden', sa.Float(), nullable=True),
    sa.Column('registrace_14denni_uspesnost', sa.Float(), nullable=True),
    sa.Column('registrace_14denni_uspesnost_zmena_den', sa.Float(), nullable=True),
    sa.Column('registrace_14denni_uspesnost_zmena_tyden', sa.Float(), nullable=True),
    sa.Column('registrace_30denni_uspesnost', sa.Float(), nullable=True),
    sa.Column('registrace_30denni_uspesnost_zmena_den', sa.Float(), nullable=True),
    sa.Column('registrace_30denni_uspesnost_zmena_tyden', sa.Float(), nullable=True),
    sa.Column('registrace_prumer_cekani', sa.Float(), nullable=True),
    sa.Column('registrace_prumer_cekani_zmena_den', sa.Float(), nullable=True),
    sa.Column('registrace_prumer_cekani_zmena_tyden', sa.Float(), nullable=True),
    sa.Column('registrace_fronta_prumer_cekani', sa.Float(), nullable=True),
    sa.Column('registrace_fronta_prumer_cekani_zmena_den', sa.Float(), nullable=True),
    sa.Column('registrace_fronta_prumer_cekani_zmena_tyden', sa.Float(), nullable=True),
    sa.Column('ockovani_pocet_davek', sa.Integer(), nullable=True),
    sa.Column('ockovani_pocet_davek_zmena_den', sa.Integer(), nullable=True),
    sa.Column('ockovani_pocet_davek_zmena_tyden', sa.Integer(), nullable=True),
    sa.Column('ockovani_pocet_castecne', sa.Integer(), nullable=True),
    sa.Column('ockovani_pocet_castecne_zmena_den', sa.Integer(), nullable=True),
    sa.Column('ockovani_pocet_castecne_zmena_tyden', sa.Integer(), nullable=True),
    sa.Column('ockovani_pocet_plne', sa.Integer(), nullable=True),
    sa.Column('ockovani_pocet_plne_zmena_den', sa.Integer(), nullable=True),
    sa.Column('ockovani_pocet_plne_zmena_tyden', sa.Integer(), nullable=True),
    sa.Column('vakciny_prijate_pocet', sa.Integer(), nullable=True),
    sa.Column('vakciny_prijate_pocet_zmena_den', sa.Integer(), nullable=True),
    sa.Column('vakciny_prijate_pocet_zmena_tyden', sa.Integer(), nullable=True),
    sa.Column('vakciny_ockovane_pocet', sa.Integer(), nullable=True),
    sa.Column('vakciny_ockovane_pocet_zmena_den', sa.Integer(), nullable=True),
    sa.Column('vakciny_ockovane_pocet_zmena_tyden', sa.Integer(), nullable=True),
    sa.Column('vakciny_znicene_pocet', sa.Integer(), nullable=True),
    sa.Column('vakciny_znicene_pocet_zmena_den', sa.Integer(), nullable=True),
    sa.Column('vakciny_znicene_pocet_zmena_tyden', sa.Integer(), nullable=True),
    sa.Column('vakciny_skladem_pocet', sa.Integer(), nullable=True),
    sa.Column('vakciny_skladem_pocet_zmena_den', sa.Integer(), nullable=True),
    sa.Column('vakciny_skladem_pocet_zmena_tyden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum')
    )
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_castecne', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_castecne_zmena_den', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_castecne_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_davek', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_davek_zmena_den', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_davek_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_plne', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_plne_zmena_den', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_plne_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_fronta_prumer_cekani', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_fronta_prumer_cekani_zmena_den', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_fronta_prumer_cekani_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_kapacita_1', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_kapacita_1_zmena_den', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_kapacita_1_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_nejblizsi_volno', sa.Date(), nullable=True))
    op.drop_column('kraje_metriky', 'ockovani_pocet_2_zmena_tyden')
    op.drop_column('kraje_metriky', 'ockovani_pocet')
    op.drop_column('kraje_metriky', 'ockovani_pocet_zmena_den')
    op.drop_column('kraje_metriky', 'ockovani_pocet_1_zmena_tyden')
    op.drop_column('kraje_metriky', 'ockovani_pocet_2')
    op.drop_column('kraje_metriky', 'ockovani_pocet_1')
    op.drop_column('kraje_metriky', 'ockovani_pocet_1_zmena_den')
    op.drop_column('kraje_metriky', 'ockovani_pocet_2_zmena_den')
    op.drop_column('kraje_metriky', 'ockovani_pocet_zmena_tyden')
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_castecne', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_castecne_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_castecne_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_davek', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_davek_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_davek_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_plne', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_plne_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_plne_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_fronta_prumer_cekani', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_fronta_prumer_cekani_zmena_den', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_fronta_prumer_cekani_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_kapacita_1', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_kapacita_1_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_kapacita_1_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_nejblizsi_volno', sa.Date(), nullable=True))
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_2_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_1_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_2')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_1')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_1_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_2_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_zmena_tyden')
    op.add_column('okresy_metriky', sa.Column('registrace_fronta_prumer_cekani', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_fronta_prumer_cekani_zmena_den', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_fronta_prumer_cekani_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_kapacita_1', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_kapacita_1_zmena_den', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_kapacita_1_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_nejblizsi_volno', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('okresy_metriky', 'rezervace_nejblizsi_volno')
    op.drop_column('okresy_metriky', 'rezervace_kapacita_1_zmena_tyden')
    op.drop_column('okresy_metriky', 'rezervace_kapacita_1_zmena_den')
    op.drop_column('okresy_metriky', 'rezervace_kapacita_1')
    op.drop_column('okresy_metriky', 'registrace_fronta_prumer_cekani_zmena_tyden')
    op.drop_column('okresy_metriky', 'registrace_fronta_prumer_cekani_zmena_den')
    op.drop_column('okresy_metriky', 'registrace_fronta_prumer_cekani')
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_zmena_tyden', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_2_zmena_den', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_1_zmena_den', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_1_zmena_tyden', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_zmena_den', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_2_zmena_tyden', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ockovaci_mista_metriky', 'rezervace_nejblizsi_volno')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_kapacita_1_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_kapacita_1_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_kapacita_1')
    op.drop_column('ockovaci_mista_metriky', 'registrace_fronta_prumer_cekani_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'registrace_fronta_prumer_cekani_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_fronta_prumer_cekani')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_plne_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_plne_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_plne')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_davek_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_davek_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_davek')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_castecne_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_castecne_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_castecne')
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_zmena_tyden', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_2_zmena_den', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_1_zmena_den', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_1_zmena_tyden', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_zmena_den', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_2_zmena_tyden', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('kraje_metriky', 'rezervace_nejblizsi_volno')
    op.drop_column('kraje_metriky', 'rezervace_kapacita_1_zmena_tyden')
    op.drop_column('kraje_metriky', 'rezervace_kapacita_1_zmena_den')
    op.drop_column('kraje_metriky', 'rezervace_kapacita_1')
    op.drop_column('kraje_metriky', 'registrace_fronta_prumer_cekani_zmena_tyden')
    op.drop_column('kraje_metriky', 'registrace_fronta_prumer_cekani_zmena_den')
    op.drop_column('kraje_metriky', 'registrace_fronta_prumer_cekani')
    op.drop_column('kraje_metriky', 'ockovani_pocet_plne_zmena_tyden')
    op.drop_column('kraje_metriky', 'ockovani_pocet_plne_zmena_den')
    op.drop_column('kraje_metriky', 'ockovani_pocet_plne')
    op.drop_column('kraje_metriky', 'ockovani_pocet_davek_zmena_tyden')
    op.drop_column('kraje_metriky', 'ockovani_pocet_davek_zmena_den')
    op.drop_column('kraje_metriky', 'ockovani_pocet_davek')
    op.drop_column('kraje_metriky', 'ockovani_pocet_castecne_zmena_tyden')
    op.drop_column('kraje_metriky', 'ockovani_pocet_castecne_zmena_den')
    op.drop_column('kraje_metriky', 'ockovani_pocet_castecne')
    op.drop_table('cr_metriky')
    # ### end Alembic commands ###
