"""empty message

Revision ID: 1563fa8433e3
Revises: 65dbdf1c6488
Create Date: 2021-02-27 19:25:31.854098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1563fa8433e3'
down_revision = '65dbdf1c6488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ockovani_distribuce',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('ockovaci_misto_id', sa.Unicode(), nullable=False),
    sa.Column('ockovaci_misto_nazev', sa.Unicode(), nullable=True),
    sa.Column('kraj_nuts_kod', sa.Unicode(), nullable=True),
    sa.Column('kraj_nazev', sa.Unicode(), nullable=True),
    sa.Column('cilove_ockovaci_misto_id', sa.Unicode(), nullable=False),
    sa.Column('cilove_ockovaci_misto_nazev', sa.Unicode(), nullable=True),
    sa.Column('cilovy_kraj_kod', sa.Unicode(), nullable=True),
    sa.Column('cilovy_kraj_nazev', sa.Unicode(), nullable=True),
    sa.Column('ockovaci_latka', sa.Unicode(), nullable=False),
    sa.Column('vyrobce', sa.Unicode(), nullable=True),
    sa.Column('akce', sa.Unicode(), nullable=False),
    sa.Column('pocet_ampulek', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ockovaci_misto_id'], ['ockovaci_mista.id'], ),
    sa.PrimaryKeyConstraint('datum', 'ockovaci_misto_id', 'cilove_ockovaci_misto_id', 'ockovaci_latka', 'akce')
    )
    op.create_table('ockovani_spotreba',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('ockovaci_misto_id', sa.Unicode(), nullable=False),
    sa.Column('ockovaci_misto_nazev', sa.Unicode(), nullable=True),
    sa.Column('kraj_nuts_kod', sa.Unicode(), nullable=True),
    sa.Column('kraj_nazev', sa.Unicode(), nullable=True),
    sa.Column('ockovaci_latka', sa.Unicode(), nullable=False),
    sa.Column('vyrobce', sa.Unicode(), nullable=True),
    sa.Column('pouzite_ampulky', sa.Integer(), nullable=True),
    sa.Column('znehodnocene_ampulky', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ockovaci_misto_id'], ['ockovaci_mista.id'], ),
    sa.PrimaryKeyConstraint('datum', 'ockovaci_misto_id', 'ockovaci_latka')
    )
    op.add_column('ockovaci_mista', sa.Column('nrpzs_kod', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ockovaci_mista', 'nrpzs_kod')
    op.drop_table('ockovani_spotreba')
    op.drop_table('ockovani_distribuce')
    # ### end Alembic commands ###
