"""empty message

Revision ID: 18f99a103a26
Revises: a013636798d4
Create Date: 2021-06-25 13:42:35.536442

"""
from alembic import op
import sqlalchemy as sa
import csv
from app.models import ZdravotnickeStredisko


# revision identifiers, used by Alembic.
revision = '18f99a103a26'
down_revision = 'a013636798d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('praktici_kapacity',
    sa.Column('zdravotnicke_zarizeni_kod', sa.Unicode(), nullable=False),
    sa.Column('datum_aktualizace', sa.DateTime(), nullable=False),
    sa.Column('typ_vakciny', sa.Unicode(), nullable=False),
    sa.Column('kraj', sa.Unicode(), nullable=False),
    sa.Column('mesto', sa.Unicode(), nullable=False),
    sa.Column('nazev_ordinace', sa.Unicode(), nullable=False),
    sa.Column('adresa', sa.Unicode(), nullable=True),
    sa.Column('pocet_davek', sa.Integer(), nullable=False),
    sa.Column('kontakt_email', sa.Unicode(), nullable=True),
    sa.Column('kontakt_tel', sa.Unicode(), nullable=True),
    sa.Column('poznamka', sa.Unicode(), nullable=True),   
    sa.PrimaryKeyConstraint('zdravotnicke_zarizeni_kod', 'typ_vakciny')
    )
    op.create_table('praktici_login',
    sa.Column('zdravotnicke_zarizeni_kod', sa.Unicode(), nullable=False),
    sa.Column('heslo', sa.Unicode(), nullable=False),    
    sa.PrimaryKeyConstraint('zdravotnicke_zarizeni_kod')
    )
    op.execute('TRUNCATE TABLE zdravotnicke_stredisko')
    op.add_column('zdravotnicke_stredisko', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('zdravotnicke_stredisko', sa.Column('telefon', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

    # with open('data/export-2021-03.csv', mode='r', encoding='utf-8') as populace_file:
    #     reader = csv.reader(populace_file, delimiter=';')
    #     next(reader, None)
    #     zdrstr_arr = [{'zdravotnicke_zarizeni_id': row[0], 'pcz': row[1], 'pcdp': row[2], 'nazev_cely': row[3], 'zdravotnicke_zarizeni_kod': row[4], 'druh_zarizeni_kod': row[5], 'druh_zarizeni': row[6], 'obec': row[8], 'psc': row[9], 'ulice': row[10], 'cislo_domu': row[11], 'kraj': row[12], 'kraj_kod': row[13], 'okres': row[14], 'okres_kod': row[15], 'nrpzs_kod': row[4][:-3], 'email': row[21], 'telefon': row[17] } for row in reader]

    # print(zdrstr_arr)

    # op.bulk_insert(ZdravotnickeStredisko.__table__, zdrstr_arr)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('praktici_login')
    op.drop_table('praktici_kapacity')
    op.drop_column('zdravotnicke_stredisko', 'email')
    op.drop_column('zdravotnicke_stredisko', 'telefon')
    # ### end Alembic commands ###
