"""empty message

Revision ID: 2a85252aeb80
Revises: c0793125b4bd
Create Date: 2021-09-26 00:49:09.323941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a85252aeb80'
down_revision = 'c0793125b4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_3_bydl', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_3_bydl_zmena_den', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_3_bydl_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_castecne_bydl', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_castecne_bydl_zmena_den', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_castecne_bydl_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_plne_bydl', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_plne_bydl_zmena_den', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('ockovani_pocet_plne_bydl_zmena_tyden', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kraje_metriky', 'ockovani_pocet_plne_bydl_zmena_tyden')
    op.drop_column('kraje_metriky', 'ockovani_pocet_plne_bydl_zmena_den')
    op.drop_column('kraje_metriky', 'ockovani_pocet_plne_bydl')
    op.drop_column('kraje_metriky', 'ockovani_pocet_castecne_bydl_zmena_tyden')
    op.drop_column('kraje_metriky', 'ockovani_pocet_castecne_bydl_zmena_den')
    op.drop_column('kraje_metriky', 'ockovani_pocet_castecne_bydl')
    op.drop_column('kraje_metriky', 'ockovani_pocet_3_bydl_zmena_tyden')
    op.drop_column('kraje_metriky', 'ockovani_pocet_3_bydl_zmena_den')
    op.drop_column('kraje_metriky', 'ockovani_pocet_3_bydl')
    # ### end Alembic commands ###
