"""empty message

Revision ID: 376213fd27c7
Revises: 0a03ba37cdc3
Create Date: 2021-03-06 20:53:00.184140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376213fd27c7'
down_revision = '0a03ba37cdc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ockovani_distribuce', sa.Column('pocet_davek', sa.Integer(), nullable=True))
    op.add_column('ockovani_spotreba', sa.Column('pouzite_davky', sa.Integer(), nullable=True))
    op.add_column('ockovani_spotreba', sa.Column('znehodnocene_davky', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ockovani_spotreba', 'znehodnocene_davky')
    op.drop_column('ockovani_spotreba', 'pouzite_davky')
    op.drop_column('ockovani_distribuce', 'pocet_davek')
    # ### end Alembic commands ###
