"""empty message

Revision ID: 3a67357dc57c
Revises: 6d30bda90e50
Create Date: 2021-03-11 18:55:54.819416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a67357dc57c'
down_revision = '6d30bda90e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_celkem', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_celkem_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_fronta', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_fronta_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_prumerne_cekani', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_prumerne_cekani_zmena_den', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_tydenni_uspesnost', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_tydenni_uspesnost_zmena_den', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_cekajici', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_cekajici_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_celkem', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_celkem_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_prijate_pocet', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_prijate_pocet_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_prijate_pocet_zmena_tyden', sa.Integer(), nullable=True))
    op.drop_column('ockovaci_mista_metriky', 'hodnota_str')
    op.drop_column('ockovaci_mista_metriky', 'typ_metriky')
    op.drop_column('ockovaci_mista_metriky', 'hodnota_int')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ockovaci_mista_metriky', sa.Column('hodnota_int', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('typ_metriky', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('ockovaci_mista_metriky', sa.Column('hodnota_str', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ockovaci_mista_metriky', 'vakciny_prijate_pocet_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_prijate_pocet_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_prijate_pocet')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_celkem_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_celkem')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_cekajici_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_cekajici')
    op.drop_column('ockovaci_mista_metriky', 'registrace_tydenni_uspesnost_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_tydenni_uspesnost')
    op.drop_column('ockovaci_mista_metriky', 'registrace_prumerne_cekani_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_prumerne_cekani')
    op.drop_column('ockovaci_mista_metriky', 'registrace_fronta_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_fronta')
    op.drop_column('ockovaci_mista_metriky', 'registrace_celkem_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_celkem')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet')
    # ### end Alembic commands ###
