"""empty message

Revision ID: 49ee1eec2be8
Revises: d99e9c5e147a
Create Date: 2021-03-14 20:54:50.321824

"""
from alembic import op
import sqlalchemy as sa
import csv
from app.models import ZdravotnickeStredisko

# revision identifiers, used by Alembic.
revision = '49ee1eec2be8'
down_revision = 'd99e9c5e147a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zdravotnicke_stredisko',
    sa.Column('zdravotnicke_zarizeni_id', sa.Integer(), nullable=False),
    sa.Column('pcz', sa.Integer(), nullable=True),
    sa.Column('pcdp', sa.Integer(), nullable=True),
    sa.Column('nazev_cely', sa.Unicode(), nullable=True),
    sa.Column('zdravotnicke_zarizeni_kod', sa.Unicode(), nullable=True),
    sa.Column('druh_zarizeni_kod', sa.Integer(), nullable=True),
    sa.Column('druh_zarizeni', sa.Unicode(), nullable=True),
    sa.Column('obec', sa.Unicode(), nullable=True),
    sa.Column('psc', sa.Unicode(), nullable=True),
    sa.Column('ulice', sa.Unicode(), nullable=True),
    sa.Column('cislo_domu', sa.Unicode(), nullable=True),
    sa.Column('kraj', sa.Unicode(), nullable=True),
    sa.Column('kraj_kod', sa.Unicode(), nullable=True),
    sa.Column('okres', sa.Unicode(), nullable=True),
    sa.Column('okres_kod', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('zdravotnicke_zarizeni_id')
    )
    # ### end Alembic commands ###
    
    with open('data/export-2021-03.csv', mode='r', encoding='utf-8') as populace_file:
        reader = csv.reader(populace_file, delimiter=';')
        next(reader, None)
        populace_arr = [{'zdravotnicke_zarizeni_id': row[0], 'pcz': row[1], 'pcdp': row[2], 'nazev_cely': row[3], 'zdravotnicke_zarizeni_kod': row[4], 'druh_zarizeni_kod': row[5], 'druh_zarizeni': row[6], 'obec': row[7], 'psc': row[8], 'ulice': row[9], 'cislo_domu': row[10], 'kraj': row[11], 'kraj_kod': row[12], 'okres': row[13], 'okres_kod': row[14]} for row in reader]

    print(populace_arr)

    op.bulk_insert(Populace.__table__, populace_arr)




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zdravotnicke_stredisko')
    # ### end Alembic commands ###
