"""empty message

Revision ID: 4fb680cb7642
Revises: 09855c27cf19
Create Date: 2021-04-03 12:19:42.628295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb680cb7642'
down_revision = '09855c27cf19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nakazeni',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('vek', sa.Integer(), nullable=False),
    sa.Column('kraj_nuts_kod', sa.Unicode(), nullable=False),
    sa.Column('pocet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum', 'vek', 'kraj_nuts_kod')
    )
    op.create_table('umrti',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('vek', sa.Integer(), nullable=False),
    sa.Column('kraj_nuts_kod', sa.Unicode(), nullable=False),
    sa.Column('pocet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum', 'vek', 'kraj_nuts_kod')
    )
    op.drop_column('ockovaci_mista', 'odkaz')
    op.drop_column('ockovaci_mista', 'operation_id')
    op.drop_column('ockovaci_mista', 'service_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ockovaci_mista', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista', sa.Column('operation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista', sa.Column('odkaz', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('umrti')
    op.drop_table('nakazeni')
    # ### end Alembic commands ###
