"""empty message

Revision ID: 518096119dae
Revises: 130cce777d35
Create Date: 2021-08-20 19:22:35.569164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518096119dae'
down_revision = '130cce777d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ockovaci_mista_detail',
    sa.Column('ockovaci_misto_id', sa.Unicode(), nullable=False),
    sa.Column('typ', sa.Unicode(), nullable=True),
    sa.Column('deti', sa.Boolean(), nullable=True),
    sa.Column('drive_in', sa.Boolean(), nullable=True),
    sa.Column('upresneni_polohy', sa.Unicode(), nullable=True),
    sa.Column('platba_karta', sa.Boolean(), nullable=True),
    sa.Column('platba_hotovost', sa.Boolean(), nullable=True),
    sa.Column('telefon', sa.Unicode(), nullable=True),
    sa.Column('email', sa.Unicode(), nullable=True),
    sa.Column('odkaz', sa.Unicode(), nullable=True),
    sa.Column('poznamka', sa.Unicode(), nullable=True),
    sa.Column('verejna_poznamka', sa.Unicode(), nullable=True),
    sa.Column('vakciny', sa.ARRAY(sa.Unicode()), nullable=True),
    sa.Column('presun_2davky_nepovolen', sa.Boolean(), nullable=True),
    sa.Column('presun_2davky_linka', sa.Boolean(), nullable=True),
    sa.Column('presun_2davky_centrum', sa.Boolean(), nullable=True),
    sa.Column('presun_2davky_telefon', sa.Unicode(), nullable=True),
    sa.Column('presun_2davky_email', sa.Unicode(), nullable=True),
    sa.Column('presun_2davky_online', sa.Boolean(), nullable=True),
    sa.Column('presun_2davky_poznamka', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['ockovaci_misto_id'], ['ockovaci_mista.id'], ),
    sa.PrimaryKeyConstraint('ockovaci_misto_id')
    )
    op.create_table('provozni_doba',
    sa.Column('ockovaci_misto_id', sa.Unicode(), nullable=False),
    sa.Column('den', sa.Integer(), nullable=True),
    sa.Column('od', sa.Unicode(), nullable=True),
    sa.Column('do', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['ockovaci_misto_id'], ['ockovaci_mista.id'], ),
    sa.PrimaryKeyConstraint('ockovaci_misto_id', 'den', 'od', 'do')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provozni_doba')
    op.drop_table('ockovaci_mista_detail')
    # ### end Alembic commands ###
