"""empty message

Revision ID: 5406a27a7927
Revises: cfadf5075d65
Create Date: 2021-03-08 20:59:06.092814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5406a27a7927'
down_revision = 'cfadf5075d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volna_mista_den')
    op.drop_table('volna_mista_cas')
    op.add_column('importy', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('ockovani_distribuce', 'cilove_ockovaci_misto_nazev')
    op.drop_column('ockovani_distribuce', 'kraj_nuts_kod')
    op.drop_column('ockovani_distribuce', 'ockovaci_misto_nazev')
    op.drop_column('ockovani_distribuce', 'cilovy_kraj_nazev')
    op.drop_column('ockovani_distribuce', 'kraj_nazev')
    op.drop_column('ockovani_distribuce', 'cilovy_kraj_kod')
    op.drop_constraint('ockovani_registrace_import_id_fkey', 'ockovani_registrace', type_='foreignkey')
    op.create_foreign_key(None, 'ockovani_registrace', 'importy', ['import_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ockovani_rezervace_import_id_fkey', 'ockovani_rezervace', type_='foreignkey')
    op.create_foreign_key(None, 'ockovani_rezervace', 'importy', ['import_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ockovani_spotreba', 'ockovaci_misto_nazev')
    op.drop_column('ockovani_spotreba', 'kraj_nazev')
    op.drop_column('ockovani_spotreba', 'kraj_nuts_kod')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ockovani_spotreba', sa.Column('kraj_nuts_kod', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ockovani_spotreba', sa.Column('kraj_nazev', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ockovani_spotreba', sa.Column('ockovaci_misto_nazev', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ockovani_rezervace', type_='foreignkey')
    op.create_foreign_key('ockovani_rezervace_import_id_fkey', 'ockovani_rezervace', 'importy', ['import_id'], ['id'])
    op.drop_constraint(None, 'ockovani_registrace', type_='foreignkey')
    op.create_foreign_key('ockovani_registrace_import_id_fkey', 'ockovani_registrace', 'importy', ['import_id'], ['id'])
    op.add_column('ockovani_distribuce', sa.Column('cilovy_kraj_kod', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ockovani_distribuce', sa.Column('kraj_nazev', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ockovani_distribuce', sa.Column('cilovy_kraj_nazev', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ockovani_distribuce', sa.Column('ockovaci_misto_nazev', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ockovani_distribuce', sa.Column('kraj_nuts_kod', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ockovani_distribuce', sa.Column('cilove_ockovaci_misto_nazev', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('importy', 'date')
    op.create_table('volna_mista_cas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cas_ziskani', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('misto_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('datum', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cas', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('volna_mista', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['importy.id'], name='volna_mista_cas_import_id_fkey'),
    sa.ForeignKeyConstraint(['misto_id'], ['ockovaci_mista.id'], name='volna_mista_cas_misto_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='volna_mista_cas_pkey')
    )
    op.create_table('volna_mista_den',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cas_ziskani', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('misto_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('datum', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('volna_mista', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['importy.id'], name='volna_mista_den_import_id_fkey'),
    sa.ForeignKeyConstraint(['misto_id'], ['ockovaci_mista.id'], name='volna_mista_den_misto_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='volna_mista_den_pkey')
    )
    # ### end Alembic commands ###
