"""empty message

Revision ID: 56677667b01a
Revises: d0ff680fad37
Create Date: 2021-07-08 21:55:27.899990

"""
from alembic import op
import sqlalchemy as sa
import csv
from app.models import ZdravotnickeStredisko

# revision identifiers, used by Alembic.
revision = '56677667b01a'
down_revision = 'd0ff680fad37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE zdravotnicke_stredisko')
    op.add_column('zdravotnicke_stredisko', sa.Column('gps_latitude', sa.Unicode(), nullable=True))
    op.add_column('zdravotnicke_stredisko', sa.Column('gps_longitude', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###
    with open('data/export-2021-03.csv', mode='r', encoding='utf-8') as populace_file:
        reader = csv.reader(populace_file, delimiter=';')
        next(reader, None)
        zdrstr_arr = [{'zdravotnicke_zarizeni_id': row[0], 'pcz': row[1], 'pcdp': row[2], 'nazev_cely': row[3], 'zdravotnicke_zarizeni_kod': row[4], 'druh_zarizeni_kod': row[5], 'druh_zarizeni': row[6], 'obec': row[8], 'psc': row[9], 'ulice': row[10], 'cislo_domu': row[11], 'kraj': row[12], 'kraj_kod': row[13], 'okres': row[14], 'okres_kod': row[15], 'nrpzs_kod': row[4][:-3], 'email': row[21], 'telefon': row[17], 'gps_latitude': 0 if row[43] == '' else row[43].split()[0], 'gps_longitude': 0 if row[43] == '' else row[43].split()[1] } for row in reader]

    # print(zdrstr_arr)

    op.bulk_insert(ZdravotnickeStredisko.__table__, zdrstr_arr)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zdravotnicke_stredisko', 'gps_longitude')
    op.drop_column('zdravotnicke_stredisko', 'gps_latitude')
    # ### end Alembic commands ###
