"""empty message

Revision ID: 594b0121cb88
Revises: eb78bc8f5c77
Create Date: 2021-10-18 19:35:58.000186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594b0121cb88'
down_revision = 'eb78bc8f5c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ockovaci_mista_detail', sa.Column('davky', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ockovaci_mista_detail', 'davky')
    # ### end Alembic commands ###
