"""empty message

Revision ID: 61a3c54cbe7f
Revises: b3e73cf868d6
Create Date: 2021-04-07 22:01:58.104818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a3c54cbe7f'
down_revision = 'b3e73cf868d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uzis_modely_05_hospitalizovani',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vek_kat', sa.Unicode(), nullable=True),
    sa.Column('pohlavi', sa.Unicode(), nullable=True),
    sa.Column('kraj_bydliste', sa.Unicode(), nullable=True),
    sa.Column('kraj_prvni_nemocnice', sa.Unicode(), nullable=True),
    sa.Column('datum_priznaku', sa.Date(), nullable=True),
    sa.Column('datum_odberu', sa.Date(), nullable=True),
    sa.Column('datum_positivity', sa.Date(), nullable=True),
    sa.Column('stav_dle_khs', sa.Unicode(), nullable=True),
    sa.Column('zahajeni_hosp', sa.Date(), nullable=True),
    sa.Column('posledni_zaznam', sa.Date(), nullable=True),
    sa.Column('stav_posledni_zaznam', sa.Unicode(), nullable=True),
    sa.Column('posledni_hosp_zaznam', sa.Unicode(), nullable=True),
    sa.Column('nejtezsi_stav', sa.Unicode(), nullable=True),
    sa.Column('tezky_stav', sa.Boolean(), nullable=True),
    sa.Column('tezky_stav_pocatek', sa.Date(), nullable=True),
    sa.Column('dni_tezky_stav', sa.Integer(), nullable=True),
    sa.Column('tezky_stav_posledni', sa.Date(), nullable=True),
    sa.Column('jip', sa.Boolean(), nullable=True),
    sa.Column('jip_pocatek', sa.Date(), nullable=True),
    sa.Column('dni_jip', sa.Integer(), nullable=True),
    sa.Column('jip_posledni', sa.Date(), nullable=True),
    sa.Column('kyslik', sa.Boolean(), nullable=True),
    sa.Column('kyslik_pocatek', sa.Date(), nullable=True),
    sa.Column('dni_kyslik', sa.Integer(), nullable=True),
    sa.Column('kyslik_posledni', sa.Date(), nullable=True),
    sa.Column('upv', sa.Boolean(), nullable=True),
    sa.Column('upv_pocatek', sa.Date(), nullable=True),
    sa.Column('dni_upv', sa.Integer(), nullable=True),
    sa.Column('upv_posledni', sa.Date(), nullable=True),
    sa.Column('ecmo', sa.Boolean(), nullable=True),
    sa.Column('ecmo_pocatek', sa.Date(), nullable=True),
    sa.Column('dni_ecmo', sa.Integer(), nullable=True),
    sa.Column('ecmo_posledni', sa.Date(), nullable=True),
    sa.Column('umrti', sa.Boolean(), nullable=True),
    sa.Column('datum_umrti', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uzis_modely_05_hospitalizovani_kraj_bydliste'), 'uzis_modely_05_hospitalizovani', ['kraj_bydliste'], unique=False)
    op.create_index(op.f('ix_uzis_modely_05_hospitalizovani_kraj_prvni_nemocnice'), 'uzis_modely_05_hospitalizovani', ['kraj_prvni_nemocnice'], unique=False)
    op.create_index(op.f('ix_uzis_modely_05_hospitalizovani_vek_kat'), 'uzis_modely_05_hospitalizovani', ['vek_kat'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uzis_modely_05_hospitalizovani_vek_kat'), table_name='uzis_modely_05_hospitalizovani')
    op.drop_index(op.f('ix_uzis_modely_05_hospitalizovani_kraj_prvni_nemocnice'), table_name='uzis_modely_05_hospitalizovani')
    op.drop_index(op.f('ix_uzis_modely_05_hospitalizovani_kraj_bydliste'), table_name='uzis_modely_05_hospitalizovani')
    op.drop_table('uzis_modely_05_hospitalizovani')
    # ### end Alembic commands ###
