"""empty message

Revision ID: 67005612bb74
Revises: 915031b7317f
Create Date: 2021-12-16 20:50:30.121056

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '67005612bb74'
down_revision = '915031b7317f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zdravotnicke_stredisko', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('zdravotnicke_stredisko', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zdravotnicke_stredisko', 'longitude')
    op.drop_column('zdravotnicke_stredisko', 'latitude')
    # ### end Alembic commands ###
