"""empty message

Revision ID: 67005612bb74
Revises: 915031b7317f
Create Date: 2021-12-16 20:50:30.121056

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '67005612bb74'
down_revision = '915031b7317f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zdravotnicke_stredisko', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('zdravotnicke_stredisko', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('kraje', sa.Column('nazev_kratky', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE kraje SET nazev = 'Hlavní město Praha', nazev_kratky = 'Praha' WHERE id = 'CZ010'")
    op.execute("UPDATE kraje SET nazev = 'Středočeský kraj', nazev_kratky = 'Středočeský' WHERE id = 'CZ020'")
    op.execute("UPDATE kraje SET nazev = 'Jihočeský kraj', nazev_kratky = 'Jihočeský' WHERE id = 'CZ031'")
    op.execute("UPDATE kraje SET nazev = 'Plzeňský kraj', nazev_kratky = 'Plzeňský' WHERE id = 'CZ032'")
    op.execute("UPDATE kraje SET nazev = 'Karlovarský kraj', nazev_kratky = 'Karlovarský' WHERE id = 'CZ041'")
    op.execute("UPDATE kraje SET nazev = 'Ústecký kraj', nazev_kratky = 'Ústecký' WHERE id = 'CZ042'")
    op.execute("UPDATE kraje SET nazev = 'Liberecký kraj', nazev_kratky = 'Liberecký' WHERE id = 'CZ051'")
    op.execute("UPDATE kraje SET nazev = 'Královéhradecký kraj', nazev_kratky = 'Královéhradecký' WHERE id = 'CZ052'")
    op.execute("UPDATE kraje SET nazev = 'Pardubický kraj', nazev_kratky = 'Pardubický' WHERE id = 'CZ053'")
    op.execute("UPDATE kraje SET nazev = 'Kraj Vysočina', nazev_kratky = 'Vysočina' WHERE id = 'CZ063'")
    op.execute("UPDATE kraje SET nazev = 'Jihomoravský kraj', nazev_kratky = 'Jihomoravský' WHERE id = 'CZ064'")
    op.execute("UPDATE kraje SET nazev = 'Olomoucký kraj', nazev_kratky = 'Olomoucký' WHERE id = 'CZ071'")
    op.execute("UPDATE kraje SET nazev = 'Zlínský kraj', nazev_kratky = 'Zlínský' WHERE id = 'CZ072'")
    op.execute("UPDATE kraje SET nazev = 'Moravskoslezský kraj', nazev_kratky = 'Moravskoslezský' WHERE id = 'CZ080'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zdravotnicke_stredisko', 'longitude')
    op.drop_column('zdravotnicke_stredisko', 'latitude')
    op.drop_column('kraje', 'nazev_kratky')
    # ### end Alembic commands ###

    op.execute("UPDATE kraje SET nazev = 'Praha' WHERE id = 'CZ010'")
    op.execute("UPDATE kraje SET nazev = 'Středočeský' WHERE id = 'CZ020'")
    op.execute("UPDATE kraje SET nazev = 'Jihočeský' WHERE id = 'CZ031'")
    op.execute("UPDATE kraje SET nazev = 'Plzeňský' WHERE id = 'CZ032'")
    op.execute("UPDATE kraje SET nazev = 'Karlovarský' WHERE id = 'CZ041'")
    op.execute("UPDATE kraje SET nazev = 'Ústecký' WHERE id = 'CZ042'")
    op.execute("UPDATE kraje SET nazev = 'Liberecký' WHERE id = 'CZ051'")
    op.execute("UPDATE kraje SET nazev = 'Královéhradecký' WHERE id = 'CZ052'")
    op.execute("UPDATE kraje SET nazev = 'Pardubický' WHERE id = 'CZ053'")
    op.execute("UPDATE kraje SET nazev = 'Vysočina' WHERE id = 'CZ063'")
    op.execute("UPDATE kraje SET nazev = 'Jihomoravský' WHERE id = 'CZ064'")
    op.execute("UPDATE kraje SET nazev = 'Olomoucký' WHERE id = 'CZ071'")
    op.execute("UPDATE kraje SET nazev = 'Zlínský' WHERE id = 'CZ072'")
    op.execute("UPDATE kraje SET nazev = 'Moravskoslezský' WHERE id = 'CZ080'")
