"""empty message

Revision ID: 6dfd4b41bc2e
Revises: 
Create Date: 2021-02-26 16:16:42.784743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfd4b41bc2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kraje',
    sa.Column('id', sa.Unicode(), nullable=False),
    sa.Column('nazev', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('okresy',
    sa.Column('id', sa.Unicode(), nullable=False),
    sa.Column('nazev', sa.Unicode(), nullable=True),
    sa.Column('kraj_id', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['kraj_id'], ['kraje.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ockovaci_mista',
    sa.Column('id', sa.Unicode(), nullable=False),
    sa.Column('nazev', sa.Unicode(), nullable=True),
    sa.Column('okres_id', sa.Unicode(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('adresa', sa.Unicode(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('minimalni_kapacita', sa.Integer(), nullable=True),
    sa.Column('bezbarierovy_pristup', sa.Boolean(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('odkaz', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['okres_id'], ['okresy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volna_mista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('cas_ziskani', sa.DateTime(), nullable=True),
    sa.Column('misto_id', sa.Unicode(), nullable=True),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('cas', sa.Unicode(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('volna_mista', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('user_service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['importy.id'], ),
    sa.ForeignKeyConstraint(['misto_id'], ['ockovaci_mista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volna_mista_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('cas_ziskani', sa.DateTime(), nullable=True),
    sa.Column('misto_id', sa.Unicode(), nullable=True),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['importy.id'], ),
    sa.ForeignKeyConstraint(['misto_id'], ['ockovaci_mista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volna_mista_raw')
    op.drop_table('volna_mista')
    op.drop_table('ockovaci_mista')
    op.drop_table('okresy')
    op.drop_table('kraje')
    op.drop_table('importy')
    # ### end Alembic commands ###
