"""empty message

Revision ID: 73729bd3913e
Revises: b8604a1102c8
Create Date: 2021-03-08 21:01:07.906088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73729bd3913e'
down_revision = 'b8604a1102c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'importy', ['date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'importy', type_='unique')
    # ### end Alembic commands ###
