"""empty message

Revision ID: 79a74d44198f
Revises: 65dbdf1c6488
Create Date: 2021-02-27 17:56:14.998816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a74d44198f'
down_revision = '65dbdf1c6488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ockovani_distribuce',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('ockovaci_misto_id', sa.Unicode(), nullable=False),
    sa.Column('ockovaci_misto_nazev', sa.Unicode(), nullable=True),
    sa.Column('kraj_nuts_kod', sa.Unicode(), nullable=True),
    sa.Column('kraj_nazev', sa.Unicode(), nullable=True),
    sa.Column('cilove_ockovaci_misto_id', sa.Unicode(), nullable=False),
    sa.Column('cilove_ockovaci_misto_nazev', sa.Unicode(), nullable=True),
    sa.Column('cilovy_kraj_kod', sa.Unicode(), nullable=True),
    sa.Column('cilovy_kraj_nazev', sa.Unicode(), nullable=True),
    sa.Column('ockovaci_latka', sa.Unicode(), nullable=False),
    sa.Column('vyrobce', sa.Unicode(), nullable=True),
    sa.Column('akce', sa.Unicode(), nullable=False),
    sa.Column('pocet_ampulek', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum', 'ockovaci_misto_id', 'cilove_ockovaci_misto_id', 'ockovaci_latka', 'akce')
    )
    op.create_table('ockovani_spotreba',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('ockovaci_misto_id', sa.Unicode(), nullable=False),
    sa.Column('ockovaci_misto_nazev', sa.Unicode(), nullable=True),
    sa.Column('kraj_nuts_kod', sa.Unicode(), nullable=True),
    sa.Column('kraj_nazev', sa.Unicode(), nullable=True),
    sa.Column('ockovaci_latka', sa.Unicode(), nullable=False),
    sa.Column('vyrobce', sa.Unicode(), nullable=True),
    sa.Column('pouzite_ampulky', sa.Integer(), nullable=True),
    sa.Column('znehodnocene_ampulky', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum', 'ockovaci_misto_id', 'ockovaci_latka')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ockovani_spotreba')
    op.drop_table('ockovani_distribuce')
    # ### end Alembic commands ###
