"""empty message

Revision ID: 7d8eb6017782
Revises: 5480e96df417
Create Date: 2021-10-07 20:58:11.151967

"""
import pandas as pd
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from app.models import ObceORP, PopulaceOrp

revision = '7d8eb6017782'
down_revision = '5480e96df417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charakteristika_obci',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('kraj_kod', sa.Unicode(), nullable=False),
    sa.Column('okres_kod', sa.Unicode(), nullable=False),
    sa.Column('orp_kod', sa.Unicode(), nullable=False),
    sa.Column('nove_pripady', sa.Integer(), nullable=True),
    sa.Column('aktivni_pripady', sa.Integer(), nullable=True),
    sa.Column('nove_pripady_65', sa.Integer(), nullable=True),
    sa.Column('nove_pripady_7_dni', sa.Integer(), nullable=True),
    sa.Column('nove_pripady_14_dni', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum', 'kraj_kod', 'okres_kod', 'orp_kod')
    )

    op.create_table('populace_orp',
    sa.Column('orp_kod', sa.Unicode(), nullable=False),
    sa.Column('pocet', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('orp_kod')
    )

    op.add_column('obce_orp', sa.Column('ruian_kod', sa.Integer(), nullable=True))

    connection = op.get_bind()

    df = pd.read_csv('data/populace_orp.csv', delimiter=';')
    df['orp_kod'] = df['orp_kod'].astype(str)
    df.to_sql(PopulaceOrp.__tablename__, connection, if_exists='replace', index=False)

    df = pd.read_csv('data/obce_orp.csv', delimiter=';')
    df['kod_obce_orp'] = df['kod_obce_orp'].astype(str)
    df['uzis_orp'] = df['uzis_orp'].astype(str)
    df = df[['kod_obce_orp', 'nazev_obce', 'okres_nuts', 'kraj_nuts', 'aken', 'uzis_orp', 'ruian_kod']]
    df.to_sql(ObceORP.__tablename__, connection, if_exists='replace', index=False)

    op.add_column('ockovani_lide', sa.Column('orp_bydl_kod', sa.Unicode(), nullable=True))
    op.execute("UPDATE ockovani_lide SET orp_bydl_kod = '-'")
    op.execute('ALTER TABLE ockovani_lide DROP CONSTRAINT ockovani_lide_pkey')
    op.create_primary_key('ockovani_lide_pkey', 'ockovani_lide', [
        'datum', 'vakcina', 'zarizeni_kod', 'poradi_davky', 'vekova_skupina', 'kraj_bydl_nuts', 'orp_bydl_kod',
        'indikace_zdravotnik', 'indikace_socialni_sluzby', 'indikace_ostatni', 'indikace_pedagog',
        'indikace_skolstvi_ostatni', 'indikace_bezpecnostni_infrastruktura', 'indikace_chronicke_onemocneni'])

    op.alter_column('populace', 'orp_kod',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('populace', 'pocet',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('populace', 'vek',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_foreign_key(None, 'vakcinacka', 'ockovaci_mista', ['misto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vakcinacka', type_='foreignkey')
    op.alter_column('populace', 'vek',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('populace', 'pocet',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('populace', 'orp_kod',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('ockovani_lide', 'orp_bydl_kod')
    op.drop_column('obce_orp', 'ruian_kod')
    op.drop_table('populace_orp')
    op.drop_table('charakteristika_obci')
    # ### end Alembic commands ###
