"""empty message

Revision ID: 7e7069a4604c
Revises: 518096119dae
Create Date: 2021-09-19 08:58:39.699824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7069a4604c'
down_revision = '518096119dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('praktici_kapacity', sa.Column('deti', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('praktici_kapacity', 'deti')
    # ### end Alembic commands ###
