"""empty message

Revision ID: 7e7069a4604c
Revises: a3fb0e170fc6
Create Date: 2021-09-22 00:00:39.699824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7069a4604c'
down_revision = 'a3fb0e170fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('praktici_kapacity', sa.Column('deti', sa.Boolean(), nullable=True))
    op.execute("UPDATE praktici_kapacity SET deti=false")
    op.alter_column('praktici_kapacity', 'deti', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('praktici_kapacity', 'deti')
    # ### end Alembic commands ###
