"""empty message

Revision ID: 81f76668f234
Revises: 25ebc99f8107
Create Date: 2021-05-06 22:12:52.115589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f76668f234'
down_revision = '25ebc99f8107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ockovaci_zarizeni',
    sa.Column('id', sa.Unicode(), nullable=False),
    sa.Column('zarizeni_nazev', sa.Unicode(), nullable=True),
    sa.Column('provoz_zahajen', sa.Boolean(), nullable=True),
    sa.Column('okres_id', sa.Unicode(), nullable=True),
    sa.Column('zrizovatel_kod', sa.Integer(), nullable=True),
    sa.Column('zrizovatel_nazev', sa.Unicode(), nullable=True),
    sa.Column('provoz_ukoncen', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['okres_id'], ['okresy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ockovaci_zarizeni')
    # ### end Alembic commands ###
