"""empty message

Revision ID: 826214f7a245
Revises: a40343f5691f
Create Date: 2021-03-12 22:34:04.948863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826214f7a245'
down_revision = 'a40343f5691f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_pocet_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_celkem', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_celkem_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_fronta', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_fronta_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_odhad_cekani', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_odhad_cekani_zmena_den', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_prumer_cekani', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_prumer_cekani_zmena_den', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_tydenni_uspesnost', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_tydenni_uspesnost_zmena_den', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_cekajici', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_cekajici_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_celkem', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_celkem_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_ockovane_pocet', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_ockovane_pocet_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_ockovane_pocet_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_prijate_pocet', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_prijate_pocet_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_prijate_pocet_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_vydane_pocet', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_vydane_pocet_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_vydane_pocet_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_znicene_pocet', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_znicene_pocet_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_znicene_pocet_zmena_tyden', sa.Integer(), nullable=True))
    op.drop_column('ockovaci_mista_metriky', 'typ_metriky')
    op.drop_column('ockovaci_mista_metriky', 'hodnota_int')
    op.drop_column('ockovaci_mista_metriky', 'hodnota_str')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ockovaci_mista_metriky', sa.Column('hodnota_str', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('hodnota_int', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('typ_metriky', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('ockovaci_mista_metriky', 'vakciny_znicene_pocet_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_znicene_pocet_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_znicene_pocet')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_vydane_pocet_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_vydane_pocet_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_vydane_pocet')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_prijate_pocet_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_prijate_pocet_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_prijate_pocet')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_ockovane_pocet_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_ockovane_pocet_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_ockovane_pocet')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_celkem_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_celkem')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_cekajici_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_cekajici')
    op.drop_column('ockovaci_mista_metriky', 'registrace_tydenni_uspesnost_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_tydenni_uspesnost')
    op.drop_column('ockovaci_mista_metriky', 'registrace_prumer_cekani_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_prumer_cekani')
    op.drop_column('ockovaci_mista_metriky', 'registrace_odhad_cekani_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_odhad_cekani')
    op.drop_column('ockovaci_mista_metriky', 'registrace_fronta_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_fronta')
    op.drop_column('ockovaci_mista_metriky', 'registrace_celkem_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_celkem')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_pocet')
    # ### end Alembic commands ###
