"""empty message

Revision ID: 9022c4d83df2
Revises: 67005612bb74
Create Date: 2021-12-25 21:36:28.841989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9022c4d83df2'
down_revision = '67005612bb74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zarizeni_metriky',
    sa.Column('zarizeni_id', sa.Unicode(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('ockovani_pocet_davek', sa.Integer(), nullable=True),
    sa.Column('ockovani_pocet_davek_zmena_den', sa.Integer(), nullable=True),
    sa.Column('ockovani_pocet_davek_zmena_tyden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('zarizeni_id', 'datum')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zarizeni_metriky')
    # ### end Alembic commands ###
