"""empty message

Revision ID: 9544fe5355f8
Revises: 5480e96df417
Create Date: 2021-10-04 21:57:14.953973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9544fe5355f8'
down_revision = '5480e96df417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charakteristika_obci',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('kraj_kod', sa.Unicode(), nullable=False),
    sa.Column('okres_kod', sa.Unicode(), nullable=False),
    sa.Column('orp_kod', sa.Unicode(), nullable=False),
    sa.Column('nove_pripady', sa.Integer(), nullable=True),
    sa.Column('aktivni_pripady', sa.Integer(), nullable=True),
    sa.Column('nove_pripady_65', sa.Integer(), nullable=True),
    sa.Column('nove_pripady_7_dni', sa.Integer(), nullable=True),
    sa.Column('nove_pripady_14_dni', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum', 'kraj_kod', 'okres_kod', 'orp_kod')
    )
    op.create_table('populace_orp',
    sa.Column('orp_kod', sa.Unicode(), nullable=False),
    sa.Column('pocet', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('orp_kod')
    )
    op.add_column('ockovani_lide', sa.Column('orp_bydl_kod', sa.Unicode(), nullable=True))
    op.execute("UPDATE ockovani_lide SET orp_bydl_kod = '-'")
    op.execute('ALTER TABLE ockovani_lide DROP CONSTRAINT ockovani_lide_pkey')
    op.create_primary_key('ockovani_lide_pkey', 'ockovani_lide', [
        'datum', 'vakcina', 'zarizeni_kod', 'poradi_davky', 'vekova_skupina', 'kraj_bydl_nuts', 'orp_bydl_kod',
        'indikace_zdravotnik', 'indikace_socialni_sluzby', 'indikace_ostatni', 'indikace_pedagog',
        'indikace_skolstvi_ostatni', 'indikace_bezpecnostni_infrastruktura', 'indikace_chronicke_onemocneni'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ockovani_lide', 'orp_bydl_kod')
    op.drop_table('populace_orp')
    op.drop_table('charakteristika_obci')
    # ### end Alembic commands ###
