"""empty message

Revision ID: 97b4fcf044a0
Revises: c703c687dcbf
Create Date: 2021-04-12 23:26:07.579397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97b4fcf044a0'
down_revision = 'c703c687dcbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cr_metriky', sa.Column('registrace_rezervace_prumer', sa.Float(), nullable=True))
    op.add_column('cr_metriky', sa.Column('registrace_rezervace_prumer_zmena_den', sa.Float(), nullable=True))
    op.add_column('cr_metriky', sa.Column('registrace_rezervace_prumer_zmena_tyden', sa.Float(), nullable=True))
    op.alter_column('dodavky_vakcin', 'datum',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('dodavky_vakcin', 'vyrobce',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'dodavky_vakcin', 'vakciny', ['vyrobce'], ['vyrobce'])
    op.add_column('kraje_metriky', sa.Column('registrace_rezervace_prumer', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_rezervace_prumer_zmena_den', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_rezervace_prumer_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_rezervace_prumer', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_rezervace_prumer_zmena_den', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_rezervace_prumer_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_rezervace_prumer', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_rezervace_prumer_zmena_den', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_rezervace_prumer_zmena_tyden', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('okresy_metriky', 'registrace_rezervace_prumer_zmena_tyden')
    op.drop_column('okresy_metriky', 'registrace_rezervace_prumer_zmena_den')
    op.drop_column('okresy_metriky', 'registrace_rezervace_prumer')
    op.drop_column('ockovaci_mista_metriky', 'registrace_rezervace_prumer_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'registrace_rezervace_prumer_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_rezervace_prumer')
    op.drop_column('kraje_metriky', 'registrace_rezervace_prumer_zmena_tyden')
    op.drop_column('kraje_metriky', 'registrace_rezervace_prumer_zmena_den')
    op.drop_column('kraje_metriky', 'registrace_rezervace_prumer')
    op.drop_constraint(None, 'dodavky_vakcin', type_='foreignkey')
    op.alter_column('dodavky_vakcin', 'vyrobce',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('dodavky_vakcin', 'datum',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('cr_metriky', 'registrace_rezervace_prumer_zmena_tyden')
    op.drop_column('cr_metriky', 'registrace_rezervace_prumer_zmena_den')
    op.drop_column('cr_metriky', 'registrace_rezervace_prumer')
    # ### end Alembic commands ###
