"""empty message

Revision ID: 9d4efdfb8a52
Revises: e1bc70696bb8
Create Date: 2024-04-18 19:12:30.918857

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9d4efdfb8a52'
down_revision = 'e1bc70696bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vakciny', sa.Column('nemoc', sa.Unicode(), nullable=True))
    op.execute("update vakciny set nemoc='Covid-19'")
    op.alter_column('vakciny', 'nemoc', existing_type=sa.Unicode(), nullable=False)

    op.add_column('praktici_kapacity', sa.Column('nemoc', sa.Unicode(), nullable=True))
    op.execute("update praktici_kapacity set nemoc='Covid-19'")
    op.alter_column('praktici_kapacity', 'nemoc', existing_type=sa.Unicode(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vakciny', 'nemoc')
    op.drop_column('praktici_kapacity', 'nemoc')
    # ### end Alembic commands ###
