"""empty message

Revision ID: a40343f5691f
Revises: 6d30bda90e50
Create Date: 2021-03-12 20:53:53.175430

"""
from alembic import op
import sqlalchemy as sa
import csv
from app.models import Populace

# revision identifiers, used by Alembic.
revision = 'a40343f5691f'
down_revision = '6d30bda90e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('populace',
    sa.Column('orp_kod', sa.Unicode(), nullable=False),
    sa.Column('pocet', sa.Integer(), nullable=False),
    sa.Column('vek', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('orp_kod', 'pocet', 'vek')
    )

    # FILE WAS REPLACED BY NEW VERSION
    #
    # with open('data/populace.csv', mode='r', encoding='utf-8') as populace_file:
    #     reader = csv.reader(populace_file, delimiter=';')
    #     next(reader, None)
    #     populace_arr = [{'orp_kod': row[0], 'pocet': row[1], 'vek': row[2]} for row in reader]
    #
    # print(populace_arr)
    #
    # op.bulk_insert(Populace.__table__, populace_arr)
    #
    # FILE WAS REPLACED BY NEW VERSION

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('populace')
    # ### end Alembic commands ###
