"""empty message

Revision ID: a6a13d882096
Revises: 1ed9516441be
Create Date: 2021-04-30 22:17:07.258216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a13d882096'
down_revision = '1ed9516441be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ockovani_lide_profese', sa.Column('indikace_bezpecnostni_infrastruktura', sa.Boolean(), nullable=False))
    op.add_column('ockovani_lide_profese', sa.Column('indikace_chronicke_onemocneni', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ockovani_lide_profese', 'indikace_chronicke_onemocneni')
    op.drop_column('ockovani_lide_profese', 'indikace_bezpecnostni_infrastruktura')
    # ### end Alembic commands ###
