"""empty message

Revision ID: a7251630aeb6
Revises: b3623a352bec
Create Date: 2021-03-22 22:18:01.480117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7251630aeb6'
down_revision = 'b3623a352bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ockovani_lide_enh',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('vakcina', sa.Unicode(), nullable=False),
    sa.Column('kraj_nuts_kod', sa.Unicode(), nullable=True),
    sa.Column('zarizeni_kod', sa.Unicode(), nullable=False),
    sa.Column('poradi_davky', sa.Integer(), nullable=False),
    sa.Column('vekova_skupina', sa.Unicode(), nullable=False),
    sa.Column('pohlavi', sa.Unicode(), nullable=False),
    sa.Column('okres_bydliste_kod', sa.Unicode(), nullable=False),
    sa.Column('indikace_zdravotnik', sa.Boolean(), nullable=False),
    sa.Column('indikace_socialni_sluzby', sa.Boolean(), nullable=False),
    sa.Column('indikace_ostatni', sa.Boolean(), nullable=False),
    sa.Column('indikace_pedagog', sa.Boolean(), nullable=False),
    sa.Column('indikace_skolstvi_ostatni', sa.Boolean(), nullable=False),
    sa.Column('pocet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum', 'vakcina', 'zarizeni_kod', 'poradi_davky', 'vekova_skupina', 'pohlavi', 'okres_bydliste_kod', 'indikace_zdravotnik', 'indikace_socialni_sluzby', 'indikace_ostatni', 'indikace_pedagog', 'indikace_skolstvi_ostatni')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ockovani_lide_enh')
    # ### end Alembic commands ###
