"""empty message

Revision ID: b073627deba3
Revises: eb41821d2f4c
Create Date: 2021-11-27 22:42:17.123695

"""
import pandas as pd
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from app.models import KapacityNemocnicStare

revision = 'b073627deba3'
down_revision = 'eb41821d2f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kapacity_nemocnic_stare',
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('zz_kod', sa.Unicode(), nullable=False),
    sa.Column('zz_nazev', sa.Unicode(), nullable=False),
    sa.Column('kraj_nuts_kod', sa.Unicode(), nullable=True),
    sa.Column('luzka_standard_kyslik_kapacita_volna_covid_pozitivni', sa.Integer(), nullable=True),
    sa.Column('luzka_standard_kyslik_kapacita_volna_covid_negativni', sa.Integer(), nullable=True),
    sa.Column('luzka_standard_kyslik_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('luzka_hfno_cpap_kapacita_volna_covid_pozitivni', sa.Integer(), nullable=True),
    sa.Column('luzka_hfno_cpap_kapacita_volna_covid_negativni', sa.Integer(), nullable=True),
    sa.Column('luzka_hfno_cpap_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('luzka_upv_niv_kapacita_volna_covid_pozitivni', sa.Integer(), nullable=True),
    sa.Column('luzka_upv_niv_kapacita_volna_covid_negativni', sa.Integer(), nullable=True),
    sa.Column('luzka_upv_niv_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('ecmo_kapacita_volna', sa.Integer(), nullable=True),
    sa.Column('ecmo_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('cvvhd_kapacita_volna', sa.Integer(), nullable=True),
    sa.Column('cvvhd_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('ventilatory_prenosne_kapacita_volna', sa.Integer(), nullable=True),
    sa.Column('ventilatory_prenosne_kapacita_celkem', sa.Integer(), nullable=True),
    sa.Column('ventilatory_operacni_sal_kapacita_volna', sa.Integer(), nullable=True),
    sa.Column('ventilatory_operacni_sal_kapacita_celkem', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum', 'zz_kod', 'zz_nazev')
    )
    # ### end Alembic commands ###

    df = pd.read_csv('data/kapacity_nemocnic_stare.csv')

    for col in df.columns:
        if col not in ['datum', 'zz_kod', 'zz_nazev', 'kraj_nuts_kod', 'kraj_nazev']:
            df[col] = df[col].fillna('0').astype('int')

    df = df.drop('kraj_nazev', axis=1)
    df.to_sql(KapacityNemocnicStare.__tablename__, op.get_bind(), if_exists='append', index=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kapacity_nemocnic_stare')
    # ### end Alembic commands ###
