"""empty message

Revision ID: b8e5763ba835
Revises: ebc18e6bef86
Create Date: 2021-08-13 20:56:57.589225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = 'b8e5763ba835'
down_revision = 'ebc18e6bef86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cr_metriky', sa.Column('registrace_pred_zavorou', sa.Integer(), nullable=True))
    op.add_column('cr_metriky', sa.Column('registrace_pred_zavorou_zmena_den', sa.Integer(), nullable=True))
    op.add_column('cr_metriky', sa.Column('registrace_pred_zavorou_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_pred_zavorou', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_pred_zavorou_zmena_den', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_pred_zavorou_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_pred_zavorou', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_pred_zavorou_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_pred_zavorou_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_pred_zavorou', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_pred_zavorou_zmena_den', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_pred_zavorou_zmena_tyden', sa.Integer(), nullable=True))

    op.add_column('ockovani_registrace', sa.Column('pocet_zmena', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    connection = op.get_bind()
    connection.execute(text("alter table ockovani_registrace add column pred_zavorou boolean default false"))
    connection.execute(text("alter table ockovani_registrace add column za_zavorou boolean default false"))
    connection.execute(text("alter table ockovani_registrace drop CONSTRAINT ockovani_registrace_part_pkey"))
    connection.execute(text("alter table ockovani_registrace add CONSTRAINT ockovani_registrace_part_pkey PRIMARY KEY (datum, ockovaci_misto_id, vekova_skupina, povolani, stat, rezervace, datum_rezervace, import_id, ockovani, pred_zavorou, za_zavorou)"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('okresy_metriky', 'registrace_pred_zavorou_zmena_tyden')
    op.drop_column('okresy_metriky', 'registrace_pred_zavorou_zmena_den')
    op.drop_column('okresy_metriky', 'registrace_pred_zavorou')
    op.drop_column('ockovaci_mista_metriky', 'registrace_pred_zavorou_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'registrace_pred_zavorou_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_pred_zavorou')
    op.drop_column('kraje_metriky', 'registrace_pred_zavorou_zmena_tyden')
    op.drop_column('kraje_metriky', 'registrace_pred_zavorou_zmena_den')
    op.drop_column('kraje_metriky', 'registrace_pred_zavorou')
    op.drop_column('cr_metriky', 'registrace_pred_zavorou_zmena_tyden')
    op.drop_column('cr_metriky', 'registrace_pred_zavorou_zmena_den')
    op.drop_column('cr_metriky', 'registrace_pred_zavorou')
    # ### end Alembic commands ###

    connection = op.get_bind()
    connection.execute(text("alter table ockovani_registrace drop column pred_zavorou"))
    connection.execute(text("alter table ockovani_registrace drop column za_zavorou"))
    connection.execute(text("alter table ockovani_registrace drop CONSTRAINT ockovani_registrace_part_pkey"))
    connection.execute(text("alter table ockovani_registrace add CONSTRAINT ockovani_registrace_part_pkey PRIMARY KEY (datum, ockovaci_misto_id, vekova_skupina, povolani, stat, rezervace, datum_rezervace, import_id, ockovani)"))
