"""empty message

Revision ID: c0793125b4bd
Revises: a3fb0e170fc6
Create Date: 2021-09-22 21:11:22.298364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0793125b4bd'
down_revision = 'a3fb0e170fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('praktici_kapacity', sa.Column('deti', sa.Boolean(), nullable=True))
    op.add_column('praktici_kapacity', sa.Column('dospeli', sa.Boolean(), nullable=True))
    op.execute("UPDATE praktici_kapacity SET deti=false")
    op.execute("UPDATE praktici_kapacity SET dospeli=true")
    op.alter_column('praktici_kapacity', 'deti', nullable=False)
    op.alter_column('praktici_kapacity', 'dospeli', nullable=False)
    op.add_column('praktici_kapacity', sa.Column('expirace', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('praktici_kapacity', 'expirace')
    op.drop_column('praktici_kapacity', 'deti')
    op.drop_column('praktici_kapacity', 'dospeli')
    # ### end Alembic commands ###
