"""empty message

Revision ID: cb94fb60af8b
Revises: eb78bc8f5c77
Create Date: 2021-10-20 21:00:13.366106

"""
from alembic import op
from sqlalchemy import text
import csv
import urllib
from app.models import ZdravotnickeStredisko

# revision identifiers, used by Alembic.
revision = 'cb94fb60af8b'
down_revision = 'eb78bc8f5c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
    connection = op.get_bind()
    connection.execute(text("truncate table zdravotnicke_stredisko"))
    
    url = "https://nrpzs.uzis.cz/res/file/export/export-2021-10.csv"    
    response = urllib.request.urlopen(url)
    lines = [l.decode('cp1250') for l in response.readlines()]
    cr = csv.reader(lines, delimiter=';')
    next(cr)
    zdrstr_arr = [{'zdravotnicke_zarizeni_id': row[0], 'pcz': row[1], 'pcdp': row[2], 'nazev_cely': row[3], 'zdravotnicke_zarizeni_kod': row[4], 'druh_zarizeni_kod': row[5], 'druh_zarizeni': row[6], 'obec': row[8], 'psc': row[9], 'ulice': row[10], 'cislo_domu': row[11], 'kraj': row[12], 'kraj_kod': row[13], 'okres': row[14], 'okres_kod': row[15], 'nrpzs_kod': row[4][:-3] } for row in cr]

    op.bulk_insert(ZdravotnickeStredisko.__table__, zdrstr_arr)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
    pass