"""empty message

Revision ID: ce339c4a95d0
Revises: b3623a352bec
Create Date: 2021-03-23 21:21:19.418060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce339c4a95d0'
down_revision = 'b3623a352bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cr_metriky', sa.Column('rezervace_cekajici_1', sa.Integer(), nullable=True))
    op.add_column('cr_metriky', sa.Column('rezervace_cekajici_1_zmena_den', sa.Integer(), nullable=True))
    op.add_column('cr_metriky', sa.Column('rezervace_cekajici_1_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('cr_metriky', sa.Column('rezervace_cekajici_2', sa.Integer(), nullable=True))
    op.add_column('cr_metriky', sa.Column('rezervace_cekajici_2_zmena_den', sa.Integer(), nullable=True))
    op.add_column('cr_metriky', sa.Column('rezervace_cekajici_2_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('cr_metriky', sa.Column('rezervace_kapacita_2', sa.Integer(), nullable=True))
    op.add_column('cr_metriky', sa.Column('rezervace_kapacita_2_zmena_den', sa.Integer(), nullable=True))
    op.add_column('cr_metriky', sa.Column('rezervace_kapacita_2_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_cekajici_1', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_cekajici_1_zmena_den', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_cekajici_1_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_cekajici_2', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_cekajici_2_zmena_den', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_cekajici_2_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_kapacita_2', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_kapacita_2_zmena_den', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_kapacita_2_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_cekajici_1', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_cekajici_1_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_cekajici_1_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_cekajici_2', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_cekajici_2_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_cekajici_2_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_kapacita_2', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_kapacita_2_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_kapacita_2_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_cekajici_1', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_cekajici_1_zmena_den', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_cekajici_1_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_cekajici_2', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_cekajici_2_zmena_den', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_cekajici_2_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_kapacita_2', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_kapacita_2_zmena_den', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_kapacita_2_zmena_tyden', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('okresy_metriky', 'rezervace_kapacita_2_zmena_tyden')
    op.drop_column('okresy_metriky', 'rezervace_kapacita_2_zmena_den')
    op.drop_column('okresy_metriky', 'rezervace_kapacita_2')
    op.drop_column('okresy_metriky', 'rezervace_cekajici_2_zmena_tyden')
    op.drop_column('okresy_metriky', 'rezervace_cekajici_2_zmena_den')
    op.drop_column('okresy_metriky', 'rezervace_cekajici_2')
    op.drop_column('okresy_metriky', 'rezervace_cekajici_1_zmena_tyden')
    op.drop_column('okresy_metriky', 'rezervace_cekajici_1_zmena_den')
    op.drop_column('okresy_metriky', 'rezervace_cekajici_1')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_kapacita_2_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_kapacita_2_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_kapacita_2')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_cekajici_2_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_cekajici_2_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_cekajici_2')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_cekajici_1_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_cekajici_1_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_cekajici_1')
    op.drop_column('kraje_metriky', 'rezervace_kapacita_2_zmena_tyden')
    op.drop_column('kraje_metriky', 'rezervace_kapacita_2_zmena_den')
    op.drop_column('kraje_metriky', 'rezervace_kapacita_2')
    op.drop_column('kraje_metriky', 'rezervace_cekajici_2_zmena_tyden')
    op.drop_column('kraje_metriky', 'rezervace_cekajici_2_zmena_den')
    op.drop_column('kraje_metriky', 'rezervace_cekajici_2')
    op.drop_column('kraje_metriky', 'rezervace_cekajici_1_zmena_tyden')
    op.drop_column('kraje_metriky', 'rezervace_cekajici_1_zmena_den')
    op.drop_column('kraje_metriky', 'rezervace_cekajici_1')
    op.drop_column('cr_metriky', 'rezervace_kapacita_2_zmena_tyden')
    op.drop_column('cr_metriky', 'rezervace_kapacita_2_zmena_den')
    op.drop_column('cr_metriky', 'rezervace_kapacita_2')
    op.drop_column('cr_metriky', 'rezervace_cekajici_2_zmena_tyden')
    op.drop_column('cr_metriky', 'rezervace_cekajici_2_zmena_den')
    op.drop_column('cr_metriky', 'rezervace_cekajici_2')
    op.drop_column('cr_metriky', 'rezervace_cekajici_1_zmena_tyden')
    op.drop_column('cr_metriky', 'rezervace_cekajici_1_zmena_den')
    op.drop_column('cr_metriky', 'rezervace_cekajici_1')
    # ### end Alembic commands ###
