"""empty message

Revision ID: cfca0dbd30f3
Revises: 0a03ba37cdc3
Create Date: 2021-03-04 22:07:57.221614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfca0dbd30f3'
down_revision = '0a03ba37cdc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('importy', sa.Column('end', sa.DateTime(), nullable=True))
    op.add_column('importy', sa.Column('last_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('importy', 'last_modified')
    op.drop_column('importy', 'end')
    # ### end Alembic commands ###
