"""empty message

Revision ID: d02dc7054d09
Revises: bc40d86be5e9
Create Date: 2021-03-17 21:39:09.620569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02dc7054d09'
down_revision = 'bc40d86be5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kraje_metriky', sa.Column('rezervace_kapacita', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_kapacita_zmena_den', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_kapacita_zmena_tyden', sa.Integer(), nullable=True))
    op.drop_column('kraje_metriky', 'vakciny_vydane_pocet_zmena_den')
    op.drop_column('kraje_metriky', 'vakciny_vydane_pocet_zmena_tyden')
    op.drop_column('kraje_metriky', 'vakciny_vydane_pocet')
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_kapacita', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_kapacita_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_kapacita_zmena_tyden', sa.Integer(), nullable=True))
    op.drop_column('ockovaci_mista_metriky', 'vakciny_vydane_pocet_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_vydane_pocet_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_vydane_pocet')
    op.add_column('okresy_metriky', sa.Column('rezervace_kapacita', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_kapacita_zmena_den', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_kapacita_zmena_tyden', sa.Integer(), nullable=True))
    op.drop_column('okresy_metriky', 'vakciny_vydane_pocet_zmena_den')
    op.drop_column('okresy_metriky', 'vakciny_vydane_pocet_zmena_tyden')
    op.drop_column('okresy_metriky', 'vakciny_vydane_pocet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('okresy_metriky', sa.Column('vakciny_vydane_pocet', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('okresy_metriky', sa.Column('vakciny_vydane_pocet_zmena_tyden', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('okresy_metriky', sa.Column('vakciny_vydane_pocet_zmena_den', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('okresy_metriky', 'rezervace_kapacita_zmena_tyden')
    op.drop_column('okresy_metriky', 'rezervace_kapacita_zmena_den')
    op.drop_column('okresy_metriky', 'rezervace_kapacita')
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_vydane_pocet', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_vydane_pocet_zmena_tyden', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_vydane_pocet_zmena_den', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ockovaci_mista_metriky', 'rezervace_kapacita_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_kapacita_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_kapacita')
    op.add_column('kraje_metriky', sa.Column('vakciny_vydane_pocet', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kraje_metriky', sa.Column('vakciny_vydane_pocet_zmena_tyden', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kraje_metriky', sa.Column('vakciny_vydane_pocet_zmena_den', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('kraje_metriky', 'rezervace_kapacita_zmena_tyden')
    op.drop_column('kraje_metriky', 'rezervace_kapacita_zmena_den')
    op.drop_column('kraje_metriky', 'rezervace_kapacita')
    # ### end Alembic commands ###
