"""empty message

Revision ID: d30325fe4fb8
Revises: e9abc8ce056d
Create Date: 2021-11-06 18:56:17.139962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd30325fe4fb8'
down_revision = 'e9abc8ce056d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provozni_doba')
    op.create_table('provozni_doba',
        sa.Column('ockovaci_misto_id', sa.Unicode(), nullable=False),
        sa.Column('den', sa.Integer(), nullable=True),
        sa.Column('od', sa.Time(), nullable=True),
        sa.Column('do', sa.Time(), nullable=True),
        sa.ForeignKeyConstraint(['ockovaci_misto_id'], ['ockovaci_mista.id'], ),
        sa.PrimaryKeyConstraint('ockovaci_misto_id', 'den', 'od', 'do')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provozni_doba')
    op.create_table('provozni_doba',
        sa.Column('ockovaci_misto_id', sa.Unicode(), nullable=False),
        sa.Column('den', sa.Integer(), nullable=True),
        sa.Column('od', sa.Unicode(), nullable=True),
        sa.Column('do', sa.Unicode(), nullable=True),
        sa.ForeignKeyConstraint(['ockovaci_misto_id'], ['ockovaci_mista.id'], ),
        sa.PrimaryKeyConstraint('ockovaci_misto_id', 'den', 'od', 'do')
    )
    # ### end Alembic commands ###
