"""empty message

Revision ID: d48be89be6f9
Revises: 81f76668f234
Create Date: 2021-06-08 20:34:46.129427

"""
from alembic import op
import sqlalchemy as sa
import csv
from app.models import Vakcinacka




# revision identifiers, used by Alembic.
revision = 'd48be89be6f9'
down_revision = '81f76668f234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vakcinacka',
    sa.Column('misto_id', sa.Unicode(), nullable=False),
    sa.Column('url_mista', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('misto_id')
    )
    # ### end Alembic commands ###

    with open('data/vakcinacka.csv', mode='r', encoding='utf-8') as vakcinacka_file:
        reader = csv.reader(vakcinacka_file, delimiter=';')
        next(reader, None)
        vakcinacka_arr = [{'misto_id': row[0], 'url_mista': row[1] } for row in reader]


    op.bulk_insert(Vakcinacka.__table__, vakcinacka_arr)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vakcinacka')
    # ### end Alembic commands ###

