"""empty message

Revision ID: d4b372f76728
Revises: e29070ed75e0
Create Date: 2022-01-10 19:28:11.998563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b372f76728'
down_revision = 'e29070ed75e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("alter table kapacity_nemocnic drop CONSTRAINT if exists kapacity_nemocnic_pkey")
    op.execute("alter table kapacity_nemocnic add CONSTRAINT kapacity_nemocnic_pkey PRIMARY KEY (datum, zz_kod, zz_nazev)")
    op.alter_column('kapacity_nemocnic', 'kraj_nuts_kod',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.alter_column('obce_orp', 'kod_obce_orp',
               existing_type=sa.TEXT(),
               nullable=False)

    op.alter_column('populace_orp', 'orp_kod',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('populace_orp', 'pocet',
               existing_type=sa.BIGINT(),
               nullable=False)

    op.add_column('vakciny', sa.Column('vakcina_sklad', sa.Unicode(), nullable=True))
    op.add_column('vakciny', sa.Column('aktivni', sa.Boolean(), nullable=True))

    op.execute("update vakciny set vakcina_sklad = vyrobce")
    op.execute("update vakciny set aktivni = true where vyrobce not in ('Novavax', 'CureVac', 'GSK')")
    op.execute("update vakciny set aktivni = false where vyrobce in ('Novavax', 'CureVac', 'GSK')")

    op.execute("insert into vakciny (vyrobce, vakcina, davky, vakcina_sklad, aktivni) VALUES('Pfizer (5-11 let)', 'Comirnaty 5-11', 2, 'Pfizer2', true) "
               "ON CONFLICT (vakcina) DO UPDATE SET vyrobce='Pfizer (5-11 let)', vakcina_sklad='Pfizer2'")

    op.alter_column('vakciny', 'vakcina_sklad', existing_type=sa.TEXT(), nullable=False)
    op.alter_column('vakciny', 'davky', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('vakciny', 'aktivni', existing_type=sa.BOOLEAN(), nullable=False)

    op.create_unique_constraint(None, 'vakciny', ['vakcina_sklad'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vakciny', 'aktivni')
    op.drop_column('vakciny', 'vakcina_sklad')
    # ### end Alembic commands ###
