"""empty message

Revision ID: d5469877223b
Revises: 55bac00887c7
Create Date: 2021-12-01 23:43:48.877347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5469877223b'
down_revision = '55bac00887c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitalizace',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('pacient_prvni_zaznam', sa.Integer(), nullable=True),
    sa.Column('kum_pacient_prvni_zaznam', sa.Integer(), nullable=True),
    sa.Column('pocet_hosp', sa.Integer(), nullable=True),
    sa.Column('stav_bez_priznaku', sa.Integer(), nullable=True),
    sa.Column('stav_lehky', sa.Integer(), nullable=True),
    sa.Column('stav_stredni', sa.Integer(), nullable=True),
    sa.Column('stav_tezky', sa.Integer(), nullable=True),
    sa.Column('jip', sa.Integer(), nullable=True),
    sa.Column('kyslik', sa.Integer(), nullable=True),
    sa.Column('hfno', sa.Integer(), nullable=True),
    sa.Column('upv', sa.Integer(), nullable=True),
    sa.Column('ecmo', sa.Integer(), nullable=True),
    sa.Column('tezky_upv_ecmo', sa.Integer(), nullable=True),
    sa.Column('umrti', sa.Integer(), nullable=True),
    sa.Column('kum_umrti', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospitalizace')
    # ### end Alembic commands ###
