"""empty message

Revision ID: d99e9c5e147a
Revises: f238461c71d7
Create Date: 2021-03-14 18:45:27.061118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99e9c5e147a'
down_revision = 'f238461c71d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kraje_metriky', sa.Column('registrace_14denni_uspesnost', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_14denni_uspesnost_zmena_den', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_14denni_uspesnost_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_30denni_uspesnost', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_30denni_uspesnost_zmena_den', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_30denni_uspesnost_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_celkem_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_fronta_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_prumer_cekani_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_tydenni_uspesnost_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_cekajici_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('rezervace_celkem_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('vakciny_skladem_pocet', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('vakciny_skladem_pocet_zmena_den', sa.Integer(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('vakciny_skladem_pocet_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_odhad_cekani_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_14denni_uspesnost', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_14denni_uspesnost_zmena_den', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_14denni_uspesnost_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_30denni_uspesnost', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_30denni_uspesnost_zmena_den', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_30denni_uspesnost_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_celkem_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_fronta_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_odhad_cekani_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_prumer_cekani_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_tydenni_uspesnost_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_cekajici_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('rezervace_celkem_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_skladem_pocet', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_skladem_pocet_zmena_den', sa.Integer(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('vakciny_skladem_pocet_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_14denni_uspesnost', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_14denni_uspesnost_zmena_den', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_14denni_uspesnost_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_30denni_uspesnost', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_30denni_uspesnost_zmena_den', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_30denni_uspesnost_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_celkem_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_fronta_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_prumer_cekani_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_tydenni_uspesnost_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_cekajici_zmena_tyden', sa.Integer(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('rezervace_celkem_zmena_tyden', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('okresy_metriky', 'rezervace_celkem_zmena_tyden')
    op.drop_column('okresy_metriky', 'rezervace_cekajici_zmena_tyden')
    op.drop_column('okresy_metriky', 'registrace_tydenni_uspesnost_zmena_tyden')
    op.drop_column('okresy_metriky', 'registrace_prumer_cekani_zmena_tyden')
    op.drop_column('okresy_metriky', 'registrace_fronta_zmena_tyden')
    op.drop_column('okresy_metriky', 'registrace_celkem_zmena_tyden')
    op.drop_column('okresy_metriky', 'registrace_30denni_uspesnost_zmena_tyden')
    op.drop_column('okresy_metriky', 'registrace_30denni_uspesnost_zmena_den')
    op.drop_column('okresy_metriky', 'registrace_30denni_uspesnost')
    op.drop_column('okresy_metriky', 'registrace_14denni_uspesnost_zmena_tyden')
    op.drop_column('okresy_metriky', 'registrace_14denni_uspesnost_zmena_den')
    op.drop_column('okresy_metriky', 'registrace_14denni_uspesnost')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_skladem_pocet_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_skladem_pocet_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'vakciny_skladem_pocet')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_celkem_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'rezervace_cekajici_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'registrace_tydenni_uspesnost_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'registrace_prumer_cekani_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'registrace_odhad_cekani_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'registrace_fronta_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'registrace_celkem_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'registrace_30denni_uspesnost_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'registrace_30denni_uspesnost_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_30denni_uspesnost')
    op.drop_column('ockovaci_mista_metriky', 'registrace_14denni_uspesnost_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'registrace_14denni_uspesnost_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_14denni_uspesnost')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_odhad_cekani_zmena_tyden')
    op.drop_column('kraje_metriky', 'vakciny_skladem_pocet_zmena_tyden')
    op.drop_column('kraje_metriky', 'vakciny_skladem_pocet_zmena_den')
    op.drop_column('kraje_metriky', 'vakciny_skladem_pocet')
    op.drop_column('kraje_metriky', 'rezervace_celkem_zmena_tyden')
    op.drop_column('kraje_metriky', 'rezervace_cekajici_zmena_tyden')
    op.drop_column('kraje_metriky', 'registrace_tydenni_uspesnost_zmena_tyden')
    op.drop_column('kraje_metriky', 'registrace_prumer_cekani_zmena_tyden')
    op.drop_column('kraje_metriky', 'registrace_fronta_zmena_tyden')
    op.drop_column('kraje_metriky', 'registrace_celkem_zmena_tyden')
    op.drop_column('kraje_metriky', 'registrace_30denni_uspesnost_zmena_tyden')
    op.drop_column('kraje_metriky', 'registrace_30denni_uspesnost_zmena_den')
    op.drop_column('kraje_metriky', 'registrace_30denni_uspesnost')
    op.drop_column('kraje_metriky', 'registrace_14denni_uspesnost_zmena_tyden')
    op.drop_column('kraje_metriky', 'registrace_14denni_uspesnost_zmena_den')
    op.drop_column('kraje_metriky', 'registrace_14denni_uspesnost')
    # ### end Alembic commands ###
