"""empty message

Revision ID: db2b53362b1c
Revises: d99e9c5e147a
Create Date: 2021-03-15 21:32:27.792471

"""
from alembic import op
import sqlalchemy as sa
import csv
from app.models import ZdravotnickeStredisko

# revision identifiers, used by Alembic.
revision = 'db2b53362b1c'
down_revision = 'd99e9c5e147a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zdravotnicke_stredisko',
    sa.Column('zdravotnicke_zarizeni_id', sa.Integer(), nullable=False),
    sa.Column('pcz', sa.Integer(), nullable=True),
    sa.Column('pcdp', sa.Integer(), nullable=True),
    sa.Column('nazev_cely', sa.Unicode(), nullable=True),
    sa.Column('zdravotnicke_zarizeni_kod', sa.Unicode(), nullable=True),
    sa.Column('druh_zarizeni_kod', sa.Integer(), nullable=True),
    sa.Column('druh_zarizeni', sa.Unicode(), nullable=True),
    sa.Column('obec', sa.Unicode(), nullable=True),
    sa.Column('psc', sa.Unicode(), nullable=True),
    sa.Column('ulice', sa.Unicode(), nullable=True),
    sa.Column('cislo_domu', sa.Unicode(), nullable=True),
    sa.Column('kraj', sa.Unicode(), nullable=True),
    sa.Column('kraj_kod', sa.Unicode(), nullable=True),
    sa.Column('okres', sa.Unicode(), nullable=True),
    sa.Column('okres_kod', sa.Unicode(), nullable=True),
    sa.Column('nrpzs_kod', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('zdravotnicke_zarizeni_id')
    )
    # ### end Alembic commands ###
    
    
    # with open('data/export-2021-03.csv', mode='r', encoding='utf-8') as populace_file:
    #     reader = csv.reader(populace_file, delimiter=';')
    #     next(reader, None)
    #     zdrstr_arr = [{'zdravotnicke_zarizeni_id': row[0], 'pcz': row[1], 'pcdp': row[2], 'nazev_cely': row[3], 'zdravotnicke_zarizeni_kod': row[4], 'druh_zarizeni_kod': row[5], 'druh_zarizeni': row[6], 'obec': row[8], 'psc': row[9], 'ulice': row[10], 'cislo_domu': row[11], 'kraj': row[12], 'kraj_kod': row[13], 'okres': row[14], 'okres_kod': row[15], 'nrpzs_kod': row[4][:-3] } for row in reader]

    # print(zdrstr_arr)

    # op.bulk_insert(ZdravotnickeStredisko.__table__, zdrstr_arr)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zdravotnicke_stredisko')
    # ### end Alembic commands ###
