"""empty message

Revision ID: e29070ed75e0
Revises: aeb805b3209b
Create Date: 2021-12-26 10:51:16.485720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29070ed75e0'
down_revision = 'aeb805b3209b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ockovani_distribuce_akce'), 'ockovani_distribuce', ['akce'], unique=False)
    op.create_index(op.f('ix_ockovani_rezervace_datum'), 'ockovani_rezervace', ['datum'], unique=False)
    op.create_index(op.f('ix_ockovani_rezervace_kalendar_ockovani'), 'ockovani_rezervace', ['kalendar_ockovani'], unique=False)
    op.create_index(op.f('ix_ockovani_rezervace_ockovaci_misto_id'), 'ockovani_rezervace', ['ockovaci_misto_id'], unique=False)
    op.create_index(op.f('ix_ockovani_spotreba_ockovaci_misto_id'), 'ockovani_spotreba', ['ockovaci_misto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ockovani_spotreba_ockovaci_misto_id'), table_name='ockovani_spotreba')
    op.drop_index(op.f('ix_ockovani_rezervace_ockovaci_misto_id'), table_name='ockovani_rezervace')
    op.drop_index(op.f('ix_ockovani_rezervace_kalendar_ockovani'), table_name='ockovani_rezervace')
    op.drop_index(op.f('ix_ockovani_rezervace_datum'), table_name='ockovani_rezervace')
    op.drop_index(op.f('ix_ockovani_distribuce_akce'), table_name='ockovani_distribuce')
    # ### end Alembic commands ###
