"""empty message

Revision ID: e5ef53428817
Revises: 55bac00887c7
Create Date: 2021-12-01 19:14:48.170430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ef53428817'
down_revision = '55bac00887c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cr_metriky', sa.Column('registrace_median_cekani', sa.Float(), nullable=True))
    op.add_column('cr_metriky', sa.Column('registrace_median_cekani_zmena_den', sa.Float(), nullable=True))
    op.add_column('cr_metriky', sa.Column('registrace_median_cekani_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_median_cekani', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_median_cekani_zmena_den', sa.Float(), nullable=True))
    op.add_column('kraje_metriky', sa.Column('registrace_median_cekani_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_median_cekani', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_median_cekani_zmena_den', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('registrace_median_cekani_zmena_tyden', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_median_cekani', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_median_cekani_zmena_den', sa.Float(), nullable=True))
    op.add_column('okresy_metriky', sa.Column('registrace_median_cekani_zmena_tyden', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('okresy_metriky', 'registrace_median_cekani_zmena_tyden')
    op.drop_column('okresy_metriky', 'registrace_median_cekani_zmena_den')
    op.drop_column('okresy_metriky', 'registrace_median_cekani')
    op.drop_column('ockovaci_mista_metriky', 'registrace_median_cekani_zmena_tyden')
    op.drop_column('ockovaci_mista_metriky', 'registrace_median_cekani_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'registrace_median_cekani')
    op.drop_column('kraje_metriky', 'registrace_median_cekani_zmena_tyden')
    op.drop_column('kraje_metriky', 'registrace_median_cekani_zmena_den')
    op.drop_column('kraje_metriky', 'registrace_median_cekani')
    op.drop_column('cr_metriky', 'registrace_median_cekani_zmena_tyden')
    op.drop_column('cr_metriky', 'registrace_median_cekani_zmena_den')
    op.drop_column('cr_metriky', 'registrace_median_cekani')
    # ### end Alembic commands ###
