"""empty message

Revision ID: e9abc8ce056d
Revises: cb94fb60af8b
Create Date: 2021-10-27 00:12:45.839199

"""
import pandas as pd
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from app.models import SrovnaniOckovani

revision = 'e9abc8ce056d'
down_revision = 'cb94fb60af8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('srovnani_ockovani',
    sa.Column('tyden', sa.Unicode(), nullable=False),
    sa.Column('vekova_skupina', sa.Unicode(), nullable=False),
    sa.Column('pozitivni_celkem', sa.Integer(), nullable=True),
    sa.Column('pozitivni_bez_ockovani', sa.Integer(), nullable=True),
    sa.Column('pozitivni_po_prvni', sa.Integer(), nullable=True),
    sa.Column('pozitivni_po_ukonceni', sa.Integer(), nullable=True),
    sa.Column('pozitivni_po_ukonceni_s_posilujici', sa.Integer(), nullable=True),
    sa.Column('hospitalizace_celkem', sa.Integer(), nullable=True),
    sa.Column('hospitalizace_bez_ockovani', sa.Integer(), nullable=True),
    sa.Column('hospitalizace_po_prvni', sa.Integer(), nullable=True),
    sa.Column('hospitalizace_po_ukonceni', sa.Integer(), nullable=True),
    sa.Column('hospitalizace_po_ukonceni_s_posilujici', sa.Integer(), nullable=True),
    sa.Column('JIP_celkem', sa.Integer(), nullable=True),
    sa.Column('JIP_bez_ockovani', sa.Integer(), nullable=True),
    sa.Column('JIP_po_prvni', sa.Integer(), nullable=True),
    sa.Column('JIP_po_ukonceni', sa.Integer(), nullable=True),
    sa.Column('JIP_po_ukonceni_s_posilujici', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tyden', 'vekova_skupina')
    )
    # ### end Alembic commands ###

    pozitivity = pd.read_excel('data/ockovani-pozitivity-hospitalizace-jip.xlsx', sheet_name=0,
                               usecols=['tyden', 'vek_kategorie', 'pozitivni_celkem', 'pozitivni_bez_ockovani',
                                        'pozitivni_po_prvni', 'pozitivni_po_ukonceni',
                                        'pozitivni_po_ukonceni_s_posilujici'])
    hospitalizace = pd.read_excel('data/ockovani-pozitivity-hospitalizace-jip.xlsx', sheet_name=1,
                                  usecols=['tyden', 'vek_kategorie', 'hospitalizace_celkem',
                                           'hospitalizace_bez_ockovani', 'hospitalizace_po_prvni',
                                           'hospitalizace_po_ukonceni', 'hospitalizace_po_ukonceni_s_posilujici'])
    jip = pd.read_excel('data/ockovani-pozitivity-hospitalizace-jip.xlsx', sheet_name=2,
                        usecols=['tyden', 'vek_kategorie', 'JIP_celkem', 'JIP_bez_ockovani', 'JIP_po_prvni',
                                 'JIP_po_ukonceni', 'JIP_po_ukonceni_s_posilujici'])

    df = pd.merge(pozitivity, hospitalizace)
    df = pd.merge(df, jip)
    df = df.rename({'vek_kategorie': 'vekova_skupina'}, axis='columns')
    df['vekova_skupina'] = df['vekova_skupina'].str.replace(' let', '')

    df.to_sql(SrovnaniOckovani.__tablename__, op.get_bind(), if_exists='append', index=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('srovnani_ockovani')
    # ### end Alembic commands ###
