"""empty message

Revision ID: eb41821d2f4c
Revises: d24853205cc7
Create Date: 2021-11-19 22:12:21.432552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb41821d2f4c'
down_revision = 'd24853205cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute("truncate table ockovani_rezervace")
    connection.execute("alter table ockovani_rezervace drop CONSTRAINT if exists ockovani_rezervace_pkey")
    connection.execute("alter table ockovani_rezervace drop CONSTRAINT if exists ockovani_rezervace_import_id_fkey")
    op.drop_column('ockovani_rezervace', 'import_id')
    connection.execute("alter table ockovani_rezervace add CONSTRAINT ockovani_rezervace_pkey PRIMARY KEY (datum, ockovaci_misto_id, kalendar_ockovani)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute("truncate table ockovani_rezervace")
    connection.execute("alter table ockovani_rezervace drop CONSTRAINT if exists ockovani_rezervace_pkey")
    op.add_column('ockovani_rezervace', sa.Column('import_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('ockovani_rezervace_import_id_fkey', 'ockovani_rezervace', 'importy', ['import_id'], ['id'], ondelete='CASCADE')
    connection.execute("alter table ockovani_rezervace add CONSTRAINT ockovani_rezervace_pkey PRIMARY KEY (datum, ockovaci_misto_id, kalendar_ockovani, import_id)")

    # ### end Alembic commands ###
