"""empty message

Revision ID: eb78bc8f5c77
Revises: 7d8eb6017782
Create Date: 2021-10-15 21:27:18.781947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb78bc8f5c77'
down_revision = '7d8eb6017782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitalizace_jip_ockovani',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('celkem', sa.Integer(), nullable=True),
    sa.Column('bez_ockovani', sa.Integer(), nullable=True),
    sa.Column('bez_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('nedokoncene_ockovani', sa.Integer(), nullable=True),
    sa.Column('nedokoncene_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('dokoncene_ockovani', sa.Integer(), nullable=True),
    sa.Column('dokoncene_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('posilujici_davka', sa.Integer(), nullable=True),
    sa.Column('posilujici_davka_vek_prumer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum')
    )
    op.create_table('hospitalizace_ockovani',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('celkem', sa.Integer(), nullable=True),
    sa.Column('bez_ockovani', sa.Integer(), nullable=True),
    sa.Column('bez_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('nedokoncene_ockovani', sa.Integer(), nullable=True),
    sa.Column('nedokoncene_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('dokoncene_ockovani', sa.Integer(), nullable=True),
    sa.Column('dokoncene_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('posilujici_davka', sa.Integer(), nullable=True),
    sa.Column('posilujici_davka_vek_prumer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum')
    )
    op.create_table('nakazeni_65_ockovani',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('celkem', sa.Integer(), nullable=True),
    sa.Column('bez_ockovani', sa.Integer(), nullable=True),
    sa.Column('bez_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('nedokoncene_ockovani', sa.Integer(), nullable=True),
    sa.Column('nedokoncene_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('dokoncene_ockovani', sa.Integer(), nullable=True),
    sa.Column('dokoncene_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('posilujici_davka', sa.Integer(), nullable=True),
    sa.Column('posilujici_davka_vek_prumer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum')
    )
    op.create_table('nakazeni_ockovani',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('celkem', sa.Integer(), nullable=True),
    sa.Column('bez_ockovani', sa.Integer(), nullable=True),
    sa.Column('bez_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('nedokoncene_ockovani', sa.Integer(), nullable=True),
    sa.Column('nedokoncene_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('dokoncene_ockovani', sa.Integer(), nullable=True),
    sa.Column('dokoncene_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('posilujici_davka', sa.Integer(), nullable=True),
    sa.Column('posilujici_davka_vek_prumer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum')
    )
    op.create_table('situace_orp',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('orp_kod', sa.Unicode(), nullable=False),
    sa.Column('incidence_7', sa.Integer(), nullable=True),
    sa.Column('incidence_65_7', sa.Integer(), nullable=True),
    sa.Column('incidence_75_7', sa.Integer(), nullable=True),
    sa.Column('prevalence', sa.Integer(), nullable=True),
    sa.Column('prevalence_65', sa.Integer(), nullable=True),
    sa.Column('prevalence_75', sa.Integer(), nullable=True),
    sa.Column('pocet_hosp', sa.Integer(), nullable=True),
    sa.Column('nove_hosp_7', sa.Integer(), nullable=True),
    sa.Column('testy_7', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum', 'orp_kod')
    )
    op.create_table('umrti_ockovani',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('celkem', sa.Integer(), nullable=True),
    sa.Column('bez_ockovani', sa.Integer(), nullable=True),
    sa.Column('bez_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('nedokoncene_ockovani', sa.Integer(), nullable=True),
    sa.Column('nedokoncene_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('dokoncene_ockovani', sa.Integer(), nullable=True),
    sa.Column('dokoncene_ockovani_vek_prumer', sa.Integer(), nullable=True),
    sa.Column('posilujici_davka', sa.Integer(), nullable=True),
    sa.Column('posilujici_davka_vek_prumer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('umrti_ockovani')
    op.drop_table('situace_orp')
    op.drop_table('nakazeni_ockovani')
    op.drop_table('nakazeni_65_ockovani')
    op.drop_table('hospitalizace_ockovani')
    op.drop_table('hospitalizace_jip_ockovani')
    # ### end Alembic commands ###
