"""empty message

Revision ID: ed6702f505d7
Revises: 826214f7a245
Create Date: 2021-03-13 17:59:47.110884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6702f505d7'
down_revision = '826214f7a245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_odhad_cekani', sa.Float(), nullable=True))
    op.add_column('ockovaci_mista_metriky', sa.Column('ockovani_odhad_cekani_zmena_den', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ockovaci_mista_metriky', 'ockovani_odhad_cekani_zmena_den')
    op.drop_column('ockovaci_mista_metriky', 'ockovani_odhad_cekani')
    # ### end Alembic commands ###
