"""empty message

Revision ID: f4bb16f1a389
Revises: d5469877223b
Create Date: 2021-12-04 12:46:02.377389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4bb16f1a389'
down_revision = 'd5469877223b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testy',
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('pocet_pcr_testy', sa.Integer(), nullable=True),
    sa.Column('pocet_ag_testy', sa.Integer(), nullable=True),
    sa.Column('typologie_test_indik_diagnosticka', sa.Integer(), nullable=True),
    sa.Column('typologie_test_indik_epidemiologicka', sa.Integer(), nullable=True),
    sa.Column('typologie_test_indik_preventivni', sa.Integer(), nullable=True),
    sa.Column('typologie_test_indik_ostatni', sa.Integer(), nullable=True),
    sa.Column('incidence_pozitivni', sa.Integer(), nullable=True),
    sa.Column('pozit_typologie_test_indik_diagnosticka', sa.Integer(), nullable=True),
    sa.Column('pozit_typologie_test_indik_epidemiologicka', sa.Integer(), nullable=True),
    sa.Column('pozit_typologie_test_indik_preventivni', sa.Integer(), nullable=True),
    sa.Column('pozit_typologie_test_indik_ostatni', sa.Integer(), nullable=True),
    sa.Column('pcr_pozit_sympt', sa.Integer(), nullable=True),
    sa.Column('pcr_pozit_asymp', sa.Integer(), nullable=True),
    sa.Column('ag_pozit_symp', sa.Integer(), nullable=True),
    sa.Column('ag_pozit_asymp_pcr_conf', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datum')
    )
    op.drop_table('ockovaci_mista_bez_registrace')
    op.drop_table('bezregistrace_fronta')
    op.drop_table('ockovaci_mista_detail')
    op.add_column('ockovaci_mista', sa.Column('typ', sa.Unicode(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('vekove_skupiny', sa.ARRAY(sa.Unicode()), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('drive_in', sa.Boolean(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('upresneni_polohy', sa.Unicode(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('platba_karta', sa.Boolean(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('platba_hotovost', sa.Boolean(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('telefon', sa.Unicode(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('email', sa.Unicode(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('odkaz', sa.Unicode(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('poznamka', sa.Unicode(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('verejna_poznamka', sa.Unicode(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('vakciny', sa.ARRAY(sa.Unicode()), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('presun_2davky_nepovolen', sa.Boolean(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('presun_2davky_linka', sa.Boolean(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('presun_2davky_centrum', sa.Boolean(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('presun_2davky_telefon', sa.Unicode(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('presun_2davky_email', sa.Unicode(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('presun_2davky_online', sa.Boolean(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('presun_2davky_poznamka', sa.Unicode(), nullable=True))
    op.add_column('ockovaci_mista', sa.Column('davky', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ockovaci_mista', 'davky')
    op.drop_column('ockovaci_mista', 'presun_2davky_poznamka')
    op.drop_column('ockovaci_mista', 'presun_2davky_online')
    op.drop_column('ockovaci_mista', 'presun_2davky_email')
    op.drop_column('ockovaci_mista', 'presun_2davky_telefon')
    op.drop_column('ockovaci_mista', 'presun_2davky_centrum')
    op.drop_column('ockovaci_mista', 'presun_2davky_linka')
    op.drop_column('ockovaci_mista', 'presun_2davky_nepovolen')
    op.drop_column('ockovaci_mista', 'vakciny')
    op.drop_column('ockovaci_mista', 'verejna_poznamka')
    op.drop_column('ockovaci_mista', 'poznamka')
    op.drop_column('ockovaci_mista', 'odkaz')
    op.drop_column('ockovaci_mista', 'email')
    op.drop_column('ockovaci_mista', 'telefon')
    op.drop_column('ockovaci_mista', 'platba_hotovost')
    op.drop_column('ockovaci_mista', 'platba_karta')
    op.drop_column('ockovaci_mista', 'upresneni_polohy')
    op.drop_column('ockovaci_mista', 'drive_in')
    op.drop_column('ockovaci_mista', 'vekove_skupiny')
    op.drop_column('ockovaci_mista', 'typ')
    op.create_table('ockovaci_mista_detail',
    sa.Column('ockovaci_misto_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('typ', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deti', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('drive_in', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('upresneni_polohy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('platba_karta', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('platba_hotovost', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('telefon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('odkaz', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('poznamka', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verejna_poznamka', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vakciny', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('presun_2davky_nepovolen', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('presun_2davky_linka', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('presun_2davky_centrum', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('presun_2davky_telefon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('presun_2davky_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('presun_2davky_online', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('presun_2davky_poznamka', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('davky', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ockovaci_misto_id'], ['ockovaci_mista.id'], name='ockovaci_mista_detail_ockovaci_misto_id_fkey'),
    sa.PrimaryKeyConstraint('ockovaci_misto_id', name='ockovaci_mista_detail_pkey')
    )
    op.create_table('bezregistrace_fronta',
    sa.Column('bezregistrace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cas_mereni', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('hodnota', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('bezregistrace_id', 'cas_mereni', name='bezregistrace_fronta_pkey')
    )
    op.create_table('ockovaci_mista_bez_registrace',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nazev', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kraj', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('kraj_kod', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nrpzs_kod', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pouzite_vakciny', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('adresa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('otviraci_doba', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('web', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kontakt_tel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('api_fronta', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dotaz_ockovani', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ockovaci_mista_bez_registrace_pkey')
    )
    op.drop_table('testy')
    # ### end Alembic commands ###
