"""empty message

Revision ID: f636a63c48d6
Revises: 10aadf62ab2a
Create Date: 2021-11-16 19:45:56.961730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f636a63c48d6'
down_revision = '10aadf62ab2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitalizace_jip_ockovani_vek',
    sa.Column('tyden', sa.Unicode(), nullable=False),
    sa.Column('tyden_od', sa.Date(), nullable=False),
    sa.Column('tyden_do', sa.Date(), nullable=False),
    sa.Column('vekova_skupina', sa.Unicode(), nullable=False),
    sa.Column('hospitalizace_jip_celkem', sa.Integer(), nullable=True),
    sa.Column('hospitalizace_jip_bez', sa.Integer(), nullable=True),
    sa.Column('hospitalizace_jip_castecne', sa.Integer(), nullable=True),
    sa.Column('hospitalizace_jip_plne', sa.Integer(), nullable=True),
    sa.Column('hospitalizace_jip_posilujici', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tyden', 'vekova_skupina')
    )
    op.create_table('hospitalizace_ockovani_vek',
    sa.Column('tyden', sa.Unicode(), nullable=False),
    sa.Column('tyden_od', sa.Date(), nullable=False),
    sa.Column('tyden_do', sa.Date(), nullable=False),
    sa.Column('vekova_skupina', sa.Unicode(), nullable=False),
    sa.Column('hospitalizace_celkem', sa.Integer(), nullable=True),
    sa.Column('hospitalizace_bez', sa.Integer(), nullable=True),
    sa.Column('hospitalizace_castecne', sa.Integer(), nullable=True),
    sa.Column('hospitalizace_plne', sa.Integer(), nullable=True),
    sa.Column('hospitalizace_posilujici', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tyden', 'vekova_skupina')
    )
    op.create_table('nakazeni_ockovani_vek',
    sa.Column('tyden', sa.Unicode(), nullable=False),
    sa.Column('tyden_od', sa.Date(), nullable=False),
    sa.Column('tyden_do', sa.Date(), nullable=False),
    sa.Column('vekova_skupina', sa.Unicode(), nullable=False),
    sa.Column('nakazeni_celkem', sa.Integer(), nullable=True),
    sa.Column('nakazeni_bez', sa.Integer(), nullable=True),
    sa.Column('nakazeni_castecne', sa.Integer(), nullable=True),
    sa.Column('nakazeni_plne', sa.Integer(), nullable=True),
    sa.Column('nakazeni_posilujici', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tyden', 'vekova_skupina')
    )
    op.drop_table('srovnani_ockovani')

    op.execute("UPDATE vakciny SET vakcina='SPIKEVAX' WHERE vyrobce='Moderna'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('srovnani_ockovani',
    sa.Column('tyden', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('od', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('do', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('vekova_skupina', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nakazeni_celkem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nakazeni_bez', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nakazeni_castecne', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nakazeni_plne', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nakazeni_posilujici', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospitalizace_celkem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospitalizace_bez', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospitalizace_castecne', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospitalizace_plne', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospitalizace_posilujici', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospitalizace_jip_celkem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospitalizace_jip_bez', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospitalizace_jip_castecne', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospitalizace_jip_plne', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospitalizace_jip_posilujici', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tyden', 'vekova_skupina', name='srovnani_ockovani_pkey')
    )
    op.drop_table('nakazeni_ockovani_vek')
    op.drop_table('hospitalizace_ockovani_vek')
    op.drop_table('hospitalizace_jip_ockovani_vek')
    # ### end Alembic commands ###
