"""empty message

Revision ID: fb644dbb9719
Revises: 9d4efdfb8a52
Create Date: 2024-04-19 16:34:57.052486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb644dbb9719'
down_revision = '9d4efdfb8a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('praktici_kapacity', schema=None) as batch_op:
        batch_op.drop_column('nazev_ordinace')
        batch_op.drop_column('mesto')
        batch_op.drop_column('adresa')
        batch_op.drop_column('kraj')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('praktici_kapacity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kraj', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('adresa', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mesto', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nazev_ordinace', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
