name: check-disk-space

on:
  schedule:
    - cron:  '00 03 * * 0'

jobs:
  deploy:
    name: DB cleanup
    environment: production
    runs-on: ubuntu-18.04
    env:
      APP_DIR: '${HOME}/prd/app'
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER_WEB: ${{ secrets.SSH_USER_WEB }}
    steps:
      - id: ip
        uses: haythem/public-ip@v1.2
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -H ${SSH_HOST} >> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          echo "${SSH_KEY}" | tr -d '\r' | ssh-add -
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
      - name: Cleanup DB
        run: ssh ${SSH_USER_WEB}@${SSH_HOST} -p ${SSH_PORT} "cd ${APP_DIR} && source venv/bin/activate && flask cleanup-db"
