name: update-free-vaccines

on:
  schedule:
    - cron:  '0/15 * * * *'

jobs:
  deploy:
    name: Update free vaccines page
    environment: production
    runs-on: ubuntu-18.04
    env:
      APP_DIR: '${HOME}/prd/app'
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER_WEB: ${{ secrets.SSH_USER_WEB }}
    steps:
      - id: ip
        uses: haythem/public-ip@v1.2
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -H ${SSH_HOST} >> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          echo "${SSH_KEY}" | tr -d '\r' | ssh-add -
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          echo "Public IP: ${{ steps.ip.outputs.ipv4 }}"
      - name: Check if webserver is running
        run: ssh ${SSH_USER_WEB}@${SSH_HOST} -p ${SSH_PORT} "systemctl status ockovani-prd.service"
      - name: Create static pages
        run: ssh ${SSH_USER_WEB}@${SSH_HOST} -p ${SSH_PORT} "cd ${APP_DIR} && bash scripts/create_free_vaccines_page.sh"
