name: update-web

on:
  workflow_dispatch

concurrency: production_env

jobs:
  deploy:
    name: Update static pages - GP
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: production
    runs-on: ubuntu-22.04
    env:
      APP_DIR: '${HOME}/prd/app'
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER_WEB: ${{ secrets.SSH_USER_WEB }}
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -H ${SSH_HOST} >> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          echo "${SSH_KEY}" | tr -d '\r' | ssh-add -
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
      - name: Check if webserver is running
        run: ssh ${SSH_USER_WEB}@${SSH_HOST} -p ${SSH_PORT} "systemctl status ockovani-prd.service"
      - name: Create static pages
        run: ssh ${SSH_USER_WEB}@${SSH_HOST} -p ${SSH_PORT} "bash ${APP_DIR}/scripts/create_static_pages_gp.sh"
